<?php
// credentials.php
return [
    "Test Project" => ["api_key" => "CE-8MJQMGPJZG98E0JO", "api_token" => "XrRS0mSPbSd6JMMNQPe0NJofVqG5njjd"],
"Democrazy" => ["api_key" => "CE-8NNRQIBZHVHUYQDY", "api_token" => "1F3mRqjeqqY9JEjO6jSAlFkNSGCwNUTX"],
"merchant-2-prd" => ["api_key" => "CE-IESXMYRKB2DGBIK4", "api_token" => "EdN2fHiKSYK1DWK2wGkOphO2CDSaErrz"],
"Meatball" => ["api_key" => "CE-XBX2LDSFFJRUN3JY", "api_token" => "Qed2fm7fzAudQ0T82Yf8LCRGwXRCOLA7"],
"Tiger" => ["api_key" => "CE-8SMCS8SIHDCVFBPT", "api_token" => "gCdJj3uy1Vm4fqittWY0lUwma3ifQgDS"],
"Alpha" => ["api_key" => "CE-Z6BZE9XONKOEED3D", "api_token" => "q3yjhzFuALaZw8EZ9p4bKcd9jM3VkUlB"],
"Hengheng" => ["api_key" => "CE-IXUKVVKB9GRHS8IK", "api_token" => "mCc5GvfzceccIQ6JUAFFEKRTN7ozX3P0"],
"Wolfgang" => ["api_key" => "CE-EBJJ00D2CIDBAA75", "api_token" => "ita9KeGCVC2BnFWoyVFnQMsF18vBo8VF"],
"Lion" => ["api_key" => "CE-EAQ0WMDRK1J7VXOY", "api_token" => "TqPA5XTTX7VQIRCkgsHpaoHfGNbresLD"],
"Rogertc" => ["api_key" => "CE-TZCJ32ZGNY2XQHC0", "api_token" => "5jl9rYiMKA26filOqNAqAbBLHlKMZ6wd"],
"Mustang" => ["api_key" => "CE-BBFRPHX4JUEQPVMG", "api_token" => "nwjbYB2sq2EZPqXRlpNVjKnd0ZiGM5O5"],
"Adjust Balance" => ["api_key" => "CE-FSHAFQWCLGDBHDUE", "api_token" => "bwwT1lFi1ZLeGrRMwEB9RddwAx2Ey75n"],
"Peacock" => ["api_key" => "CE-LVERJVF69JEE9L2X", "api_token" => "UcRbDMsgfxd63W2WZMr6XWnf8zlgJLya"],
"Silver Cooks" => ["api_key" => "CE-IZ6SP4MZ0E0DEHHG", "api_token" => "w25io9Av1WTvJTiZNhyidulJsKwheMhH"],
"D89 (inactive)" => ["api_key" => "CE-JVPSMBUQ0GG2J5IJ", "api_token" => "LIEx8zYijkwYZo6y1HBqdGxZRg4XyTGa"],
"P20" => ["api_key" => "CE-KNP8HOFMUO2E9RGC", "api_token" => "Bzi1JNxhXRnufiWnCE2lI9MW9wsZRlsO"],
"MAD" => ["api_key" => "CE-ORMDENXMARNXHOY6", "api_token" => "Arui2RUyOdmHA7SzoeSa1w5wFiegweoY"],
"D89" => ["api_key" => "CE-THH0BX952MX6BIMD", "api_token" => "VGlqLGzIH7ZJCJiHD3gt8AL4wUQ3ZLAT"],
"AMPMbet" => ["api_key" => "CE-XERT5NDGEJ0N9QMD", "api_token" => "QyWZvHr3tlg2zB8JTTarZ85RsiZ6eKtx"],
"KAS" => ["api_key" => "LAPANGAN", "api_token" => "MANILA"],
"KAS" => ["api_key" => "BESAR", "api_token" => "MANILA"],
"APW" => ["api_key" => "CE-XZZQFDPZZIU4BBU8", "api_token" => "bBwRcBCWGYWXVmGjPXcYpvMZei4i5Ofa"],
"Antzein Merchant" => ["api_key" => "CE-FR15JPKY8XPGFDXY", "api_token" => "p47s4f3gve57Pn60XLSNjbCFLDKWqGRs"],
"Pinapple" => ["api_key" => "CE-X29WCGIN6ZKWOOH2", "api_token" => "Mzr3g1JTl42KpK6mhMfdwgMhEtQc6xPs"],
"Payment" => ["api_key" => "CE-PXFGJX6VWT1IFUEB", "api_token" => "l1bdKxt2TO1dn239Z7CDExUgCy5iMQ9B"],
"RICKY" => ["api_key" => "BCP", "api_token" => "CE"],
"BCP" => ["api_key" => "CE-TD5PQXVPTRGPHN9U", "api_token" => "9ASP1GxRal3GizwgrVVegGRzjCJ5nVNK"],
"Nougat Coverpay" => ["api_key" => "CE-OHRDXCG7JPRCUOS8", "api_token" => "lp0F0Mqo0vymlt7aBcYiDqv7KEI5BSUH"],
"Panther" => ["api_key" => "CE-ITRIADWH3ZBDRLYZ", "api_token" => "ESfJ5rFKCbzC7nI14ODXUhptp5YOuEUt"],
"BComplex" => ["api_key" => "CE-UIROXES2BN1B86TW", "api_token" => "t4R8LEt8sT5IUYIlG5ocwbCIDsA5PoWm"],
"KAS" => ["api_key" => "CK", "api_token" => "CE"],
"SLJ" => ["api_key" => "CE-BUENSBGQZXMCTNR0", "api_token" => "UujE6ZDydfbOfHftSuKdIUC1oZlgTQHi"],
"Y20" => ["api_key" => "CE-VYBFT009UROUZHI3", "api_token" => "kGlKj0RpNjACJQWFOKRralOzgJNxnbhN"],
"SpnPay" => ["api_key" => "CE-FS0GQR763KLPZ3CO", "api_token" => "CHutttFyHw9knybC6epjr9ON9Z0TrcSe"],
"F1" => ["api_key" => "WD", "api_token" => "CE"],
"Synergizetech" => ["api_key" => "CE-WAIMTGWFZNISCJWS", "api_token" => "ElWQt8XJZFsAPtNeiAlrGGCm6sgdoleE"],
"Selamat (inactive)" => ["api_key" => "CE-2GBMKRNYMC9CYNJY", "api_token" => "R5kPBtOzB7OoMyesDOLI34CqdUJM8UTe"],
"Selamat" => ["api_key" => "CE-XDSU6OEDKNL4BR6R", "api_token" => "3JambLo4l0DsBKLXbWqLkLgvgu8nqsIU"],
"manggo" => ["api_key" => "CE-RI2RJNXFC55SUPGI", "api_token" => "DgUtIEiP6a8D3dWCaC278kvkGI2HRGFc"],
"Disburse" => ["api_key" => "CE-OUFTCYJ4MMEHW8VX", "api_token" => "aT7baS8OmhBMu8Tvq8s5glVJwmWMxGLp"],
"SkyNet" => ["api_key" => "CE-SBWPTYMBGLY1MTRM", "api_token" => "s5MH78TGqVe3EK6VI8dAtPKchdJLPEyv"],
"Ginger" => ["api_key" => "CE-0JWHYFXY06BTRXMM", "api_token" => "7LP4O0pYIOFP5QSwtW5FLOQtUq1hyFX8"],
"coverpaygame" => ["api_key" => "CE-JUVGWNUZHGQGX9OS", "api_token" => "o93bazCzCsdLBRCQkxK2w4RchHCmPOf6"],
"coverpaypdl" => ["api_key" => "CE-GV6FPTHWEOC1Q9SJ", "api_token" => "TOXUorJBvz4qCd97PqdjW5YPq8qWqYlw"],
"Hengcbd" => ["api_key" => "CE-CN6H6AQWYONJPWYL", "api_token" => "G3SuPVetfAP1QhR1gXNpWq2S7dA8J0kc"],
"Andre" => ["api_key" => "CE-Q1AAUBA1DPLR4CSE", "api_token" => "pkJODUrgTfdvNmW11xy03n4GS3jGIQ5a"],
"Hengin" => ["api_key" => "CE-GXLCDU2FUVR7BIRU", "api_token" => "oZGN4ESgxxkTO596qARfhhbzhEOOvtxN"],
"Hengme" => ["api_key" => "CE-6NMYSRA6OKEFX3NU", "api_token" => "0RmdYUULXXzpowjrVIfPbZH1lejCJMKE"],
"Hengars" => ["api_key" => "CE-YFEEOVU2SC2EZRUL", "api_token" => "aBXLkJryeSM3v2fb7FqpfejaIoM0MyXe"],
"Hengpay" => ["api_key" => "CE-TDL98AMVBMTY51NI", "api_token" => "ysrgDwiikPvrvgwOUOmY1fyECs3He141"],
"Hengku" => ["api_key" => "CE-X9NGBZ6C7JH6FDJR", "api_token" => "CGMFI8jK38LzXTQWy38MtSAAqtMJLjKd"],
"Hengnew" => ["api_key" => "CE-W5IAZQD1TCH8SVJC", "api_token" => "hDoZoSWTTS3GaiBwpKnuERgGS7JN7o7f"],
"Hengpul" => ["api_key" => "CE-M0COU9TTPAJNIIYE", "api_token" => "4ugasb5z0HzvTeo1fVDHlX35mhAwfU6v"],
"hengwar" => ["api_key" => "CE-AZJ2FIR1WSPGCTNG", "api_token" => "7xsgkGZVaRgYa93POW7uedFytzJbxfS5"],
"hengbet" => ["api_key" => "CE-JVQUMQCCSR7Z2N4W", "api_token" => "A3k8tBvP8VhV4ud7RkcXmQ9jFOOaxaFB"],
"henghab" => ["api_key" => "CE-M6HSOM6S1CE063DW", "api_token" => "ZHfLR6bHvTqv9tZpUNcN8EaghQMcq1Tr"],
"ugStaging" => ["api_key" => "CE-ULSOEORMBR0OIKZF", "api_token" => "wcRTOrzVG4On8SAiwBHLD88lelGhKWvp"],
"Avocado" => ["api_key" => "CE-XLFB7IRBPZYPEL2K", "api_token" => "0SKigNzxzZ6T1zTdOebLK9yGR7ESpsXT"],
"Papaya" => ["api_key" => "CE-WXX13TEGHR8UGEYT", "api_token" => "0B23FKUzlkz3ri9NoF7YzRn3Kcu5FTlN"],
"FUTURE" => ["api_key" => "CE-4IPS0WKQ5OT3RKWV", "api_token" => "jddYIdELRKXJlqEolwm1EFkK2irbl8MI"],
"Demen" => ["api_key" => "CE-IUXNDGDTL2MGO1UE", "api_token" => "UJMAiu5CJAPQIH6Sl2ko2RgLC4rqN3nZ"],
"39" => ["api_key" => "CE-Z1X0HUK4IOOXZUIP", "api_token" => "0BJ4kG1pk6IodegzGgBPP2wo1LTO0xFb"],
"Instan" => ["api_key" => "CE-WYBFAGWYHDHBNQ06", "api_token" => "o5q0eqGpQ4PlX6ZOLfrmS0ay0Nrt4nid"],
"Sultan" => ["api_key" => "CE-VTCN0SSSR5TTKPSJ", "api_token" => "61Av9B2ucmPX8HEGz1fMxpCr6A4fkw0y"],
"Sir" => ["api_key" => "CE-QSWXHXKI6DBLAYXA", "api_token" => "3EiBEQoa9d50FNlVgs8nKt7tXIEqYlv2"],
"eagle" => ["api_key" => "CE-TECYDDZETCXPNLXT", "api_token" => "U5eEOQaeineNe7HRZ9khOn9tCMH62zml"],
"Andre2" => ["api_key" => "CE-ACLG2NHL9YXZ0WNG", "api_token" => "3uc4vJNcwt1N1QJQXZDZBof5n8FrJNcL"],
"ravave" => ["api_key" => "CE-WVR178SELGXZMRBY", "api_token" => "svna7pkSeYb0pp6ao6u1F22C3Yl7FZUT"],
"ravave (inactive)" => ["api_key" => "CE-RSYTKEFDRGZYLW4B", "api_token" => "q5hQuN2ghRgm23DQWB9O0i0bRYBJHgPX"],
"Viking (inactive)" => ["api_key" => "CE-ICOEJIIQPY5FIABY", "api_token" => "CDuVF5H5SLOdt27Yuh2THTKiPBemSL8n"],
"Viking" => ["api_key" => "CE-DBVTEXTRRBC2OUNI", "api_token" => "BbV4OWT8OZgffMGR3QSPCcIVnKycw8HR"],
"Sel Darah Biru (inactive)" => ["api_key" => "CE-OEBSPY0YJCRYXLHN", "api_token" => "a1pwDMfXBDp4d5i9nBFIlSygrrp8tbP0"],
"Sel Darah Biru" => ["api_key" => "CE-CYPC6GCRMAGQZ2T3", "api_token" => "FQUW3o5p5ezB0KzZ6emcB88YJNHwCtI1"],
"Noodles" => ["api_key" => "CE-WDUL3VGB8B6E9Z3E", "api_token" => "Qq3LF0ikXK6Lo118gyGboIanrDgYxkxb"],
"Kas Teknisi Support" => ["api_key" => "CE-FCV1UYKJYRL111MZ", "api_token" => "T1pOoX6D5sMzMNgDB08aS8uUzTWp2e72"],
"FhalconJPX" => ["api_key" => "CE-CMNKTPDPQ6VAV0RO", "api_token" => "hoIQEtaDOyxQlDMYYytobhDh9jzDeMaq"],
"MWS" => ["api_key" => "CE-6GH5BXHFSKFL7LQF", "api_token" => "ZxJjVodx1TuP9utUf5WyiSC5WmcgmO9V"],
"MPB" => ["api_key" => "CE-FQL1Y4TDQGPZNNQL", "api_token" => "FlNIx1PsmaWDUAxDFwtTEeidvh4QeLZ1"],
"BRS" => ["api_key" => "CE-FOIHEA4UPGKYSEX1", "api_token" => "8KQOFuTk0J9I0jMNeejviACfqDtdXwuw"],
"ASA" => ["api_key" => "CE-5WO9ZNAZVHFXWCPI", "api_token" => "YsDoALtZejdB3WanRejueI2avDFnNSL7"],
"SMD" => ["api_key" => "CE-MCWOLQBCIMEVTVMP", "api_token" => "9EMuncsKXVG8xjbgje38NiuWvT5kkmAh"],
"Hengnaga" => ["api_key" => "CE-DUHTZSI4D8OEFLEB", "api_token" => "3HsLxe6vLK21l5OGIM0YNoYJWBZDXFLA"],
"Heng koin" => ["api_key" => "CE-KHGWUZEXGGVCZUYE", "api_token" => "6yA5vCKSwkcFKLnbRsT15YoW4bfAtulU"],
"grosir (inactive)" => ["api_key" => "CE-ZWJ3UTWEGVZP5NT0", "api_token" => "tWYSmUuOS3FwN8v2O6DqbGUaMGgNM5k0"],
"Infini" => ["api_key" => "CE-H8BPWMBJMEBFGSDC", "api_token" => "TcvqL82oDoxMErL3defzrsV6hYtccFJs"],
"Hengzon" => ["api_key" => "CE-YUYBDUIFHQGQNNT0", "api_token" => "6AqpundDg57qTEBVGKGtiqIalVQ4izeP"],
"Hengmaha" => ["api_key" => "CE-NQRNUS2A4EWVQCVD", "api_token" => "LDrzbBs5YPzpkRaBwZZprbHzy39zhlf8"],
"Hengsapu" => ["api_key" => "CE-LQMRRCM4DFL6MJC8", "api_token" => "uXqwdsU4qYZvEqD3RbrylFGkdVBTbi8u"],
"Henglot" => ["api_key" => "CE-MTDDWBPZSJALM7AF", "api_token" => "HrdC0qqwVPxF1ToBnwCn0ryEnGioLmfW"],
"Hengdol" => ["api_key" => "CE-D7G4DJKIWTUMDFSE", "api_token" => "hR5Z7EpDWT519AWyoxEI0oaVZ9mHkHxn"],
"Hengnex" => ["api_key" => "CE-LVVL1A7ZM9LDSN5A", "api_token" => "4RxrUeJ3G9q4eK17rypLwOo7WM5CV7Kk"],
"Hengtm" => ["api_key" => "CE-FDI5CBVYNO0KIFNI", "api_token" => "yQ7BtJJxPZrinqpDFhyHvEl1I2yfqBU9"],
"Ryzenith" => ["api_key" => "CE-NLVT3ASLCV57LWXZ", "api_token" => "mPKdgvShz8gkT5xbLcqZ4vKmFHb0ErOa"],
"hengholding" => ["api_key" => "CE-93UINKWKRNYRFFSJ", "api_token" => "UOexlZTWdTFJ9WrGVkccj4Xy5qQ9EW7A"],
"ExcellentPay" => ["api_key" => "CE-PNTTUSJ5PT1YBWAD", "api_token" => "fIMIjijijotwcIbIVTxFqlgYwcMkvt1L"],
"hengboya" => ["api_key" => "CE-R3GDYEYFFMWUQ3NI", "api_token" => "FMAVkWHWdlA80xWonyFhCtHz1SQuQOup"],
"Aow" => ["api_key" => "CE-J62JI7YQ9LITUGSG", "api_token" => "qhELhlH1MCEwq0x1UXhu5cdvnpBTZEcN"],
"HENGKOIN" => ["api_key" => "CE-TT5RDF6T5M5Q6AYH", "api_token" => "NsSvdkgew0vR5cEH88UJUP0x6NNHIdRy"],
"Sub Andre" => ["api_key" => "CE-EMZ0LO6W30YCBPJF", "api_token" => "z95Sp8pQ5zj70IGzkNEo4AJENV3EPZq0"],
"grosir" => ["api_key" => "CE-SJFMKOKG1HQ7REOC", "api_token" => "bFafmdOGePvExPpzQ1bj0eEoKygBP2cV"],
"Kiwi" => ["api_key" => "CE-3DPXLXMWCU8CTURW", "api_token" => "vKqhDcg5gkxHYjk7Mn7QkleG1sITbXKt"],
"Watermelon" => ["api_key" => "CE-SVKPQTGJ3LTCZTQH", "api_token" => "KR0rvh4U28wEiL5nBnUGAlUaVSdmsZsZ"],
"aowww" => ["api_key" => "CE-9MVGGSEFA4ZMUTRT", "api_token" => "Q9UubcO9zVaXidVYTsNZb3F0TPQYwojK"],
"tampung_opco" => ["api_key" => "CE-9HLPDHIJVS8WHINC", "api_token" => "Jl8pyYg7VfSXKgz6CN0FoLDTOt44c7NM"],
"GGWP tampung" => ["api_key" => "CE-7QIXVPUENUPC9WZP", "api_token" => "B8SB76EETKSlEjhVW1gMt7wL6zVfSgbu"],
"TEAM_SETTLEMENT" => ["api_key" => "CE-IJ4NXMIPYPFWTAJS", "api_token" => "9k3l3t4W6jGlZkBFWjwfHhtIRkC418Jd"],
"Alpha (zebra)" => ["api_key" => "CE-LKHD26OTYZLMWCPE", "api_token" => "bX6BRSx2uAG03A4BoZHZCHrw6CEDIPXD"],
"TEAM_GAJIAN" => ["api_key" => "CE-2LYSGFLYTQLXU7ZB", "api_token" => "tXjESY56JatE3M49LeiCv40ofcAIb8Rw"],
"Sel Darah Lain" => ["api_key" => "CE-USUZGZXWA6LGGNRW", "api_token" => "YJONDOKvojylSHTqAuHeKh7spylVlGCX"],
"Petty" => ["api_key" => "CE-SZPHDROPCWYRBIFI", "api_token" => "PeYdtBFqELZ7ZgD0OdbrUgX2Kyi4lsuQ"],
"PT" => ["api_key" => "NUMERO", "api_token" => "UNO"],
"PT MOBIL WULING BINGO" => ["api_key" => "CE-KWWSZPBEXX1CZHWV", "api_token" => "qwF4UNm8tY4Szqo8S8eGDYei010atxly"],
"wdhengpay" => ["api_key" => "CE-EGUUV8SIEF47WFK6", "api_token" => "qZOP1SS6aO2rYFrVGG3VzusQ0aTjRcgy"],
"wdhengboya" => ["api_key" => "CE-UJIGDPKCYDS7MOAQ", "api_token" => "4h3D51FEq7CUjtRqnd9dv3iuX5WTIjIl"],
"wdhengkoin" => ["api_key" => "CE-MK9AWHOVIJSHDNOS", "api_token" => "6qlY90I5RWicZF5jOpEgT7Nj2OuZ6ti0"],
"wdhenghab" => ["api_key" => "CE-EPMAIW3YLB6AA7X7", "api_token" => "Rv6NnemZJDNPisGnDx8XaOVKqi1dM5ov"],
"Intershop" => ["api_key" => "CE-PDSUFGQLMHKPRAPG", "api_token" => "1seKQdGQ9h6t18gFEaxb04Z1UTq3Obs4"],
"wdhengpul" => ["api_key" => "CE-WVDMUXRDH0QP69YX", "api_token" => "mrxAQpDfjArhnKLoZxlB3H48mniewlq5"],
"vetest2" => ["api_key" => "CE-GAKGXTIPRYCXQ9BF", "api_token" => "RF4wSlI45tX1JTpRHiAwsv6V5Qr7rpCj"],
"Coconut" => ["api_key" => "CE-8R83YQTHLK6TKNRV", "api_token" => "2cQkakR2gceIBJyWOLDdDYtpNlPnnkBG"],
"Starmart" => ["api_key" => "CE-HUF7MWXQVUYITHFG", "api_token" => "9lUuRsyEQwshKWcKtzr13sOjYuEdFz5L"],
"Tikamart" => ["api_key" => "CE-PDWFFP7PHF8GBBRR", "api_token" => "dmK9rBM7nFBvVKEIqVnSFs9IC9faLNdB"],
"Kelinci" => ["api_key" => "V01", "api_token" => "Testing"],
"Kelinci" => ["api_key" => "V02", "api_token" => "Testing"],
"Indo cell" => ["api_key" => "CE-1DH1ZUPMLRAYAQFA", "api_token" => "R8cJlyBvDaNvLC7Ix1ndJuf27TfGuwI5"],
"RoyalMart" => ["api_key" => "CE-ZPRRKBKFEHYXBIJU", "api_token" => "8z700NFo1Ab49ZXBBU1IUMooX34IAlr4"],
"Toko Jaya Abadi" => ["api_key" => "CE-K0EQNYGMG1IDHSWA", "api_token" => "HiJzYPgIENpqBZ73A2nNM1gV6gpufUne"],
"Finance" => ["api_key" => "WG", "api_token" => "CE"],
"Elephant" => ["api_key" => "CE-DN1LWE9JJJ0K96JB", "api_token" => "y9tKJ9EtGCtbK8BKeUVzXNT59RLIFHGi"],
"Macao Cell" => ["api_key" => "CE-9R4AFWD7KQ7B6W6Y", "api_token" => "j6iY7cKsjqpHzGIi1wzEbXD6bq9GaF6p"],
"WDHENGSAPU" => ["api_key" => "CE-8JLBV9RISRJJNNMJ", "api_token" => "0yJ5xFQ7xAWjDAlPDq1ctVr4YlbhCodz"],
"396 Vape" => ["api_key" => "CE-DN00XQ1Y1SIMNBCF", "api_token" => "5w9gcTo7O61FkWeCfVIwNM2IB4LsxW4u"],
"Isports Outfit" => ["api_key" => "CE-OHPUZJGSQJRMGJLC", "api_token" => "mbYymFgCluDkLwygbZn9eGx9CI9EtiWf"],
"hengsanto" => ["api_key" => "CE-IRKCTIHKNLMGKW0A", "api_token" => "xTQwtvYwplPCxod3s1lm1y9uPWiYlEYW"],
"hengharto" => ["api_key" => "CE-ODMIERPEQMPD1L5M", "api_token" => "wxHxIwkLlTMURi0sYyncHFGzGndeWMeg"],
"NEWGAME" => ["api_key" => "CE-AKUSMGIMSMKYKOME", "api_token" => "yiEyPiRv32Duj87Yekteea2YowI1IiGs"],
"Hengwdars" => ["api_key" => "CE-6GV65J1BUCMGFGC1", "api_token" => "vW6jkDMOCpP5iZhf1c85qKeU04vGXRs4"],
"wdhengnaga" => ["api_key" => "CE-STIKXN4SRRFJCNIK", "api_token" => "rAs8BmYS1mAtSkgy6CDLyEiZt5DYAIb8"],
"NEWUBUR2" => ["api_key" => "CE-91XHWJGVZQ3DYC3Q", "api_token" => "N03jszGKwBobsTOMocAsJ1F7x8hQgfOP"],
"warungjack888" => ["api_key" => "CE-ZZXONALTKNUTMDSO", "api_token" => "UV3FxMCC7r4YHujLqRlbBCxlZqGwu9ut"],
"Wbuntung10" => ["api_key" => "CE-AZ20T2AG4JKXOSBP", "api_token" => "xX9t9bXI5b7ZhTQlyD7Tc74BQpsOlThP"],
"BSW" => ["api_key" => "CE-W2RQHBPUTYPZV3MQ", "api_token" => "BQTihiwsQLSkM6kxSksZgIqs04Z5WBws"],
"QV3" => ["api_key" => "CE-XSHRW9HINVVDXURH", "api_token" => "HzmmaCmO5cFutjlJFU6JGKGCYmEHXlvO"],
"PCJ" => ["api_key" => "CE-OSTQ63V7AWCTIRAQ", "api_token" => "EhznFMU5YVsZWqhty2FQtf3ZxhnYSJlA"],
"TEAM_OPCO" => ["api_key" => "CE-75WX4VHN5LMLTJLL", "api_token" => "mh7TPEmMjwpSKwKt7gFY72ebtMK6a8oY"],
"IHK" => ["api_key" => "CE-4581XMWWAHCUTJMP", "api_token" => "GdmxKqx5NfT6ECU2YFqXxKQPOIp7HWga"],
"PNS77" => ["api_key" => "CE-KA7HG4IKQPXC67EV", "api_token" => "dP2SXPHN0YZS9RO8g1Mn8ygbaFDeoYze"],
"hengisland" => ["api_key" => "CE-6OYOGLAGKRX8S6MZ", "api_token" => "fuCRux3t7GtqCzf04FIi2nA1lQu2k5Ih"],
"Hengislandgaji" => ["api_key" => "CE-JHHQY5SUDX0ESUDA", "api_token" => "RxBy5kdWwKATcg7ByLE6dnygZdJu4cMD"],
"HSR" => ["api_key" => "CE-DAOLN8YJAO84DURQ", "api_token" => "LCTr9tjctxzMLkCn6RDKtOfG4rhLUP6B"],
"SLT" => ["api_key" => "CE-J7KS3GGGL8QPEWRZ", "api_token" => "cxTRNNPUyhfQe6MVm56ULQ2hFN8cgJXJ"],
"BMS" => ["api_key" => "CE-LCXGXTPKS15UWUE4", "api_token" => "E6bZpyBOLTc0MCWDnUKruOhvkgBlnEfq"],
"DO8" => ["api_key" => "CE-6VBH9OVB5NJWJCGY", "api_token" => "k5HnUqVuHy0frx3aVol5EK7rzZEHmjdP"],
"AH7" => ["api_key" => "CE-OE5FW63IJI20RWYI", "api_token" => "iuRmstLzFVajDqUcI8hN7XLueMijBUm8"],
"JKW" => ["api_key" => "CE-KXML7IOJSGPOHTSC", "api_token" => "tNmLs0NAb9AyWNowQ6aWmdBNAIw0Gtlx"],
"JWS" => ["api_key" => "CE-DRVVGDB5QWCENLEU", "api_token" => "RIPVlusBBk35lTXz3zFBBSHgM8ur3aSh"],
"DGJ" => ["api_key" => "CE-EUEXD8UGRMQCJWAW", "api_token" => "ii1wEQDlsq6RDqsgkVVS1lWOLzPcNixK"],
"JDC" => ["api_key" => "CE-ZDCNEBK7UBE5PMP7", "api_token" => "iPBOyl2rwc6WzviMhbZJjOdFDRRptc8F"],
"77L" => ["api_key" => "CE-DSI0RJKTAIOHLKJC", "api_token" => "2KbtUr9HZfrISIh8d2THmwsJwqYLvPGN"],
"SH7" => ["api_key" => "CE-A5SMLF8Q7SZFERNG", "api_token" => "sKHV8nJBkAQdi1y2PyPW5RcMjXYI5xu4"],
"HKW" => ["api_key" => "CE-5DNDZUAK32EKCWTM", "api_token" => "MrpxhNv1VUY7UavuCGpnQOyXkLUItBAb"],
"MAW" => ["api_key" => "CE-LVZPOGUWUS6RRCEY", "api_token" => "fWItQcuvt6Z84bKPw8z81IXdAKv56Pi1"],
"PW8" => ["api_key" => "CE-NB5AZZDSJSWANHUN", "api_token" => "KaAFV0NQ84FJqhu9iEgQshd7dZRGkooc"],
"JD2" => ["api_key" => "CE-FJGQWTKGP0Q3BGIF", "api_token" => "wfGmzAu7HgrFUzTPmkyrufeqtIMivkdo"],
"HLW" => ["api_key" => "CE-9A864QPE4RRKR6AW", "api_token" => "AsFUV2lyki3D5Z5fW4ZtlSl6TzPKtRE2"],
"DN9" => ["api_key" => "CE-W30EO5MNMEACJTYS", "api_token" => "USlj5fd95XM2mYj4KCASoVuWYy66x6Tj"],
"JUR" => ["api_key" => "CE-KGHP2JE0PT5XMS3U", "api_token" => "iwr9pxj7KmPh9TECcTefGWyB06sCivUs"],
"KUY" => ["api_key" => "CE-QCCF52HXCHQRWE7X", "api_token" => "ivdvSRgZ26J2vE52HdCTCDaYJebx782W"],
"GSP" => ["api_key" => "CE-MMKCLETAVVROBEQY", "api_token" => "VVB1BZdh6gyksizO2H9rkMV3Y4nnV4A5"],
"GH7" => ["api_key" => "CE-MNH0EFY0JA69YOJI", "api_token" => "lKwBtIZj3Xq8N4BIdWKH8XnHSO3Y1iPo"],
"HAL" => ["api_key" => "CE-ATRCU6JZJKDFOJTO", "api_token" => "lKN6BoLRhlhd2aOUDBKpNeIf6oP6J0Qu"],
"D99" => ["api_key" => "CE-ONGHXOIPJU58KZF7", "api_token" => "Jzm6HPPbkEaMKPlRyfstVjx4JIIU7qC3"],
"SAH" => ["api_key" => "CE-OREUDO6LDWUDET3U", "api_token" => "Gwp7tiRlhItRi6oAbqb6yRDMQ2xp667T"],
"M7S" => ["api_key" => "CE-PQ3ONJ18HDASGYCM", "api_token" => "E2lDESm4t2cx664QFoVS3b7aFa0E2rLO"],
"KG7" => ["api_key" => "CE-XN5BTBFPTAVELDKX", "api_token" => "L7tGnJpOqKECL83QW0WAHsf9zK91DNaF"],
"TGS" => ["api_key" => "CE-SGJTDKWXSUPEVBUF", "api_token" => "nwSKQTP3h8x3RoThLpuyMeDqBUAaRIhh"],
"HOK" => ["api_key" => "CE-FEZETT4UHNQTUUOB", "api_token" => "G7WkfZwz0UADRMGH1A2T3LDv5BtNcDnX"],
"BO7" => ["api_key" => "CE-CDOILNRYFIFZXFHT", "api_token" => "GX5rHCs0AnZaAbu2w3GxYXZH1og4OBXp"],
"SUH" => ["api_key" => "CE-D8Q8G1UY0PTRMOU7", "api_token" => "1A2j1EmROUsd3jJpDkSzJ7fffVSjUMaY"],
"BI7" => ["api_key" => "CE-QORHH3TRH0TTVO07", "api_token" => "rqAxja6LO77slACChYf8vw6TsrGIspxr"],
"HA7" => ["api_key" => "CE-OO3FQBGF3YF8EMXE", "api_token" => "3bTRPzHRssXHYrZQpkqsfsmJix7xNAsj"],
"M21" => ["api_key" => "CE-IRTWXWQ57YFS7OPB", "api_token" => "cZxZ7hi9J6GXPYmaafzgIdAPj4tpz2oy"],
"K16" => ["api_key" => "CE-KN06IVLTON4J3XMX", "api_token" => "agbrdiJSZ9iGavLPrIijlGpOF50BrHLd"],
"GAC" => ["api_key" => "CE-CTDRMOPG3USXHOFM", "api_token" => "ugdO1FrygTHY7nmeM2VcFLXYqnJzvupz"],
"M77" => ["api_key" => "CE-6COWDXZITGMGXR3Q", "api_token" => "NkyWfbkXSl80ZSDylXdbH0GgRtHIZeH2"],
"A7E" => ["api_key" => "CE-XKSHGNRADMF6XWZJ", "api_token" => "uvGyrnbDeP66ij3ZrOtB4g6M4DiJs93N"],
"GS7" => ["api_key" => "CE-RWSCVUDVTUJH6BQR", "api_token" => "T9qO1Oo814ZPeSaTZE7r7GpnWPiKr33u"],
"O7W" => ["api_key" => "CE-CRZB3IVDFYCEOGP5", "api_token" => "qKEKX3gsTiEGpDuaamEC08A1VGz330IA"],
"Wukong" => ["api_key" => "CE-B8RXGXYTEJY8YSVQ", "api_token" => "qkE04NSwwpUK3at3jNYdneDyuuxwTEv8"],
"ACE" => ["api_key" => "CE-PBYHFSWGTWFQGZBB", "api_token" => "LLESmGGIK9hEiuiS69uKiAfrI4MYDn0s"],
"VC" => ["api_key" => "CE-GKFZJSW5VEILGHEJ", "api_token" => "qNYkb4xyAEZMTLOGqf01jgKqYTLLYH3Z"],
"DRAGO-MEONG" => ["api_key" => "CE-Z0X4RYE55J8PBZZO", "api_token" => "BxNWJgxPg9ISlklka8yG9x6XHDCYipki"],
"Happy" => ["api_key" => "CE-NCZMFERGQIB29NCK", "api_token" => "Ie5FeFSpnjVMzqRez2f9bOYaXZqocirk"],
"TPST" => ["api_key" => "CE-M4R719LIV9OKFMQU", "api_token" => "YK0eCuho6uOtTIUYbanuwVR4pRdx5eFz"],
"TPRT" => ["api_key" => "CE-XXUDEH9OLUIWB2SS", "api_token" => "GFBytbhYSzctqiGeFTB1mf09jPxlUQbv"],
"OPWG" => ["api_key" => "CE-GKJYB3U3WCY8UY7O", "api_token" => "K5wgzqa5YlPM7S59C1QUITiOknwAiekK"],
"Alphazebra" => ["api_key" => "CE-BBYHQUMGWUFGCHUK", "api_token" => "ZAzWMAcBOXFy8hbDXrDhYf4UDjv35TCX"],
"BSST" => ["api_key" => "CE-FBXQTIWFFXHOJURP", "api_token" => "QZr0FC9gwM8yAOOchs6VXX9JlJ9L2tRD"],
"BSRT" => ["api_key" => "CE-4ZDUBAZGUFUOAFAQ", "api_token" => "4R3jUgIijiPbcu9Fbrsqh9YS7TuhMQIP"],
"TCST" => ["api_key" => "CE-KTGFEWBVFEPYLZOW", "api_token" => "tCrXhRVeChGgKyAwPd3aHFBg5hNhuemz"],
"TCRT" => ["api_key" => "CE-ZHR3LSJB6B36RSLN", "api_token" => "dGDnNtAHZ2RGhUJIJSRw5fQQdtMBa71y"],
"Bravo" => ["api_key" => "CE-6UK8BAHANGPB4CQ6", "api_token" => "Mbt7XM00FwTnwFQqNv2RnPaVN2TQwMql"],
"HOTEL" => ["api_key" => "-", "api_token" => "PRAGMATIC88"],
"HOTEL" => ["api_key" => "-", "api_token" => "PRAGMATIC123"],
"HOTEL" => ["api_key" => "-", "api_token" => "PRAGMATICID"],
"HOTEL" => ["api_key" => "-", "api_token" => "HOKI88CEK"],
"big777" => ["api_key" => "CE-6EEOWIAN2WZTFOZ9", "api_token" => "x3tRqzc6KqdeBZDFcfvih99LkeJgLiwp"],
"Charlie" => ["api_key" => "CE-O9NQORG7WCHZHDEA", "api_token" => "RMOE8cSd8nyfsYgZxZMDwXj9MYkWz1EL"],
"GOLF" => ["api_key" => "-", "api_token" => "GOLF"],
"GOLF" => ["api_key" => "-", "api_token" => "SULTANGACOR"],
"GOLF" => ["api_key" => "-", "api_token" => "SULTAN77"],
"GOLF" => ["api_key" => "-", "api_token" => "KAPTENKINGDOM77"],
"PGSLOT88" => ["api_key" => "CE-PPFERH8NQF6NY68E", "api_token" => "XUJcrYKUA8h24uPNVTqtbFbC99BCHsXN"],
"Delta" => ["api_key" => "CE-XUNRXFJNSBJ1TOHN", "api_token" => "pJxt6ofAm8ZWePlTmOXq7xkes9pkLlcP"],
"unoslot" => ["api_key" => "CE-SYJQDKRG6HLAC4DT", "api_token" => "S14o4hgF7aNhHuluYtotKljvGVUjXTxw"],
"Echo" => ["api_key" => "CE-AU9RBRNCMVOAUSQ9", "api_token" => "0Ye1M6Xwedy4pmr3sCvcWPCnd4IwXMGH"],
"FOXTROT" => ["api_key" => "-", "api_token" => "KOMPAS"],
"FOXTROT" => ["api_key" => "-", "api_token" => "SBOCASH"],
"FOXTROT-" => ["api_key" => "MEGA88", "api_token" => "CE"],
"FOXTROT" => ["api_key" => "-", "api_token" => "ASIA89"],
"FOXTROT" => ["api_key" => "-", "api_token" => "KEPALA4D"],
"FOXTROT" => ["api_key" => "-", "api_token" => "OSG4D"],
"slot365" => ["api_key" => "CE-ODTYO8MZJOPFWOD0", "api_token" => "cus5c8D2aiDYT2sj7vlgrFUwY0Bp5PoI"],
"Foxtrot" => ["api_key" => "CE-TVTJY0QLH16GBGE0", "api_token" => "QUTlV7NplXBa1SiTazMBir1S8pniiDew"],
"Hotel" => ["api_key" => "CE-NTXRZT3XOD3ALVBC", "api_token" => "3PU3u3pGJIpoHypV1ScHrzNLbKMwoy5h"],
"ECHO" => ["api_key" => "-", "api_token" => "JPTOTO"],
"goslot88" => ["api_key" => "CE-VJBHPFZ1DIKMWGVK", "api_token" => "8khKiMNnPB8uu3ZqDqcsqK6C5gVKr0Bh"],
"ECHO" => ["api_key" => "-", "api_token" => "FUNCITY"],
"ECHO" => ["api_key" => "-", "api_token" => "OLYMPUS88"],
"ECHO" => ["api_key" => "-", "api_token" => "DRAGON222"],
"garuda365" => ["api_key" => "CE-JLSSVRLJVJ4C5A60", "api_token" => "GkqaF6ZFahJbHAia2ifPlXp5gJU8YLGd"],
"pragmatic138" => ["api_key" => "CE-TQVOZXOSDHRYYQMP", "api_token" => "xyuEMQhcIdBg7xxLFfyJWbosFG91S2Dz"],
"DELTA" => ["api_key" => "-", "api_token" => "1POKER"],
"DELTA" => ["api_key" => "-", "api_token" => "CAKRABET"],
"DELTA" => ["api_key" => "-", "api_token" => "HOKI77"],
"DELTA" => ["api_key" => "-", "api_token" => "RAJAASIA88"],
"pgbet" => ["api_key" => "CE-NVNTGNJMYMMGY0MI", "api_token" => "zkVso4LblNaOUHpvqyShpXkxjw7LtHxD"],
"DELTA" => ["api_key" => "-", "api_token" => "SAFARI88"],
"DELTA" => ["api_key" => "-", "api_token" => "88JACKPOT"],
"DELTA" => ["api_key" => "-", "api_token" => "88CASH"],
"DELTA" => ["api_key" => "-", "api_token" => "STARXO88"],
"Vanilla" => ["api_key" => "CE-OHDPFPXXNVAIOZ8T", "api_token" => "j5wZOmhFg62KuhDOuNR6Z0bAjQ3qPh9q"],
"Pimpobyu8" => ["api_key" => "CE-97CSEITL00EJSVK6", "api_token" => "v144izuctQhpFAfTEaNHeXIGTCLrz4tK"],
"Stellaorange984" => ["api_key" => "CE-DMFIDCD2BARMXV4V", "api_token" => "ooJNKp70xa9vRJFqVpmE3hMIonOGNCWV"],
"Milk" => ["api_key" => "CE-KKV7MWKLFGSNT4J8", "api_token" => "u4Y2niVOaNcRHJynSiRR9cECurTknfz1"],
"Coffee" => ["api_key" => "CE-2VLRYGPAVVDYROXV", "api_token" => "2n6ZYphGAgjl5t7IHl3GthbqEOA3dbGE"],
"KAS" => ["api_key" => "BESAR", "api_token" => "KPS"],
"KAS" => ["api_key" => "LAPANGAN", "api_token" => "KPS"],
"CNPAY" => ["api_key" => "CE-LLPX7MSMTNDKKB5R", "api_token" => "HbRvPvZbDklC5NWd48V1fV2FPijv2EnU"],
"Gail Willms" => ["api_key" => "CE-TVBAIVKKORRD0VTY", "api_token" => "yE0w9Q0byy9eJFA4e8Lf2JOiWzycDBiE"],
"Prof. Earl Rowe" => ["api_key" => "CE-APDMZUZQ0DBFAFOA", "api_token" => "7WCv3uQ8TxfNsYL2ln49Bcn3qwmqzHCO"],
"Greta Cartwright" => ["api_key" => "CE-D02YH4L3TJBXBN03", "api_token" => "I9EEGj6F6M52u8etwMJgai1hDYo11yMy"],
"Mr. Burley Bechtelar" => ["api_key" => "V", "api_token" => "CE"],
"Rupert Fritsch" => ["api_key" => "CE-C5GXHRKITF6HQDR4", "api_token" => "W6ROjJKNKLYHIKPVQUqzr1VASjEw1OpV"],
"Robbie Batz" => ["api_key" => "CE-UOUM6U0HBDUQ1XI4", "api_token" => "cYx8L73qxjZqXZcyJYiFnNX71Nk6ikUv"],
"Mr. Walter Powlowski PhD" => ["api_key" => "CE-PKP05FP2AOPI5FJH", "api_token" => "sHx7xB17GbohiZOZYLOerk026XVStdgt"],
"Darrin Blick" => ["api_key" => "CE-JO7BPDBZ5QFVH6SH", "api_token" => "P8Th872FqAIex9RrvNiM5F5KLzhVNzdj"],
"Prof. Estel Homenick" => ["api_key" => "CE-JVYRYGLJHPU4YTY7", "api_token" => "snGbS1TR2YDIeQaVSG22n8U0mzIkfZda"],
"Mr. Perry Rath Sr." => ["api_key" => "CE-1P8HPHBEEA4UWWJI", "api_token" => "ZbyvMIUYWsXA9ibU2r2tR7OrQEwulNqn"],
"Jensen Murray" => ["api_key" => "CE-5XPZWH9U322TNHME", "api_token" => "ricLMC42nDHAS1tPHb3f84mrw7uKLr0B"],
"Lowell Grant" => ["api_key" => "CE-CPT27LIYM63VLQ4T", "api_token" => "mWMbyKRDGozXsjiIoPJgD3FL1AWLQuX0"],
"Abigail Bergstrom" => ["api_key" => "DDS", "api_token" => "CE"],
"Cassandra Kertzmann" => ["api_key" => "CE-W5WWO1BOFX9PPXGJ", "api_token" => "tfaq7StFLKUN0w4N0YlLO3oCHWv9Bcqb"],
"Cigar" => ["api_key" => "CE-JLHSSOXJ0M0I9PQN", "api_token" => "sCyetITy7jsukPFJAf6igplrvLkPBYcg"],
"RN" => ["api_key" => "CE-ESKFHZRMUFOAXUNW", "api_token" => "teaitav6huZQ3qr985Q5MeLKqdR9H5y3"],
"SPM" => ["api_key" => "CE-MOM7VWB4OXSMIY7U", "api_token" => "ArvZfXkG4LcUFzfHMzahlIh3dJZKRav5"],
"8et" => ["api_key" => "CE-QEGBYE0ZVZ1AQFAZ", "api_token" => "AnEbft5IHAJf9jzMRIaariUcYeWN4aQ3"],
"Akiat" => ["api_key" => "CE-ZSPNORXHE5EJO61L", "api_token" => "Uek2MnZ3mDBcOhP7HjS6ZkgsYko7XU30"],
"VNIX" => ["api_key" => "CE-AGOQ729CC64WMLJV", "api_token" => "YBD2HGSNbXtZXU0HQG283zYO2SXZALF0"],
"ESAFX" => ["api_key" => "CE-CAU6KZBIW5LELHPP", "api_token" => "LIsRtoQWdLV3xCd8b3mOBT7aix5Ggss3"],
"VNIX spo" => ["api_key" => "CE-MMVYIPWBOD4W55DL", "api_token" => "K5OEpJN8pmOs9ry6TNz14AZL1yoPlmxX"],
"Langit" => ["api_key" => "TMP", "api_token" => "CE"],
"Pasang" => ["api_key" => "TMP", "api_token" => "CE"],
"Gocuan" => ["api_key" => "TMP", "api_token" => "CE"],
"Fun" => ["api_key" => "TMP", "api_token" => "CE"],
"donut & froyo" => ["api_key" => "CE-DAAUEKAIRSBXK7D6", "api_token" => "QKaKkZdqz62CGc939U3MGoX3OrMa9eYB"],
"ORIENTAL" => ["api_key" => "STORE", "api_token" => "CE"],
"BELTON" => ["api_key" => "STORE", "api_token" => "CE"],
"AVIDA" => ["api_key" => "STORE", "api_token" => "CE"],
"CITYLAND" => ["api_key" => "STORE", "api_token" => "CE"],
"Pemuda" => ["api_key" => "CE-I1D4SS4AGJUODNTX", "api_token" => "g3ZWnPg9RbesB91rPtkfnpdIluPVUUxM"],
"ETON" => ["api_key" => "STORE", "api_token" => "CE"],
"SEJAHTERA88" => ["api_key" => "STORE", "api_token" => "CE"],
"S77 / Joko" => ["api_key" => "CE-6W1AQ1GLXFGZJRTS", "api_token" => "frDKttCfT93w2tLLM7TmfKc7tWdcDh7O"],
"VENUS303 [GGGAAAV]" => ["api_key" => "-", "api_token" => "GIGA1"],
"VENUS303 [GGGAAAV]" => ["api_key" => "GIGA1", "api_token" => "CE"],
"BieBieMart" => ["api_key" => "CE-EUNSUZECB2WDOUG9", "api_token" => "qR6y4Qx5i7vSCDcdPnZdwWboEQOX2tLv"],
"GIGASLOT88 [GGGAAAD]" => ["api_key" => "-", "api_token" => "GIGA"],
"ALIEN303 [GGGAAAS]" => ["api_key" => "-", "api_token" => "GIGA1"],
"MENTARI" => ["api_key" => "PULSA", "api_token" => "CE"],
"BUMI303 [GGGAAAW]" => ["api_key" => "-", "api_token" => "GIGA1"],
"VICTORIA" => ["api_key" => "STORE", "api_token" => "CE"],
"RANS303 [GGGAAAU]" => ["api_key" => "-", "api_token" => "GIGA1"],
"Erajaya Shop" => ["api_key" => "CE-IEGKWHJ9QVMXZUKN", "api_token" => "ZQEwDHKUzRk2PKsczOmAScDXq33ykxnI"],
"MEMORY" => ["api_key" => "SHOP", "api_token" => "CE"],
"RENATA" => ["api_key" => "COLLECTION", "api_token" => "SHOP"],
"7SECOND" => ["api_key" => "SHOP", "api_token" => "CE"],
"STAR" => ["api_key" => "MOON", "api_token" => "CELLULAR"],
"DATOK" => ["api_key" => "PULSA", "api_token" => "CE"],
"JURAGAN" => ["api_key" => "PONSEL", "api_token" => "CE"],
"SUSKES" => ["api_key" => "JAYA", "api_token" => "ACCESSORIES"],
"ApbMart" => ["api_key" => "CE-DFSQ8CU4EGKNIWBU", "api_token" => "Xuo2eulBJOiosw2nYoOw1fyBEg4Ja3Fb"],
"CLINTON" => ["api_key" => "STORE", "api_token" => "CE"],
"Sir Mart" => ["api_key" => "CE-Y9U6TNOJ9UU01JLW", "api_token" => "GM5NIH1fpxRF1MHcl6y17YrEMVP1fvD8"],
"Organic Market" => ["api_key" => "CE-MV21YYITCGRPRMU8", "api_token" => "qRaljpxLh7e96RMmjvx9LxD8TCAJhHHL"],
"VELGIR" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"JOS" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"Sinar Gadget" => ["api_key" => "CE-ULAW8WFVEFLAIQSP", "api_token" => "2b5EeBz3HiJTCFMKTP0QxYeen4MNtkwy"],
"WILL" => ["api_key" => "GADGET", "api_token" => "CE"],
"Toko Laris Jaya" => ["api_key" => "CE-ZW9NYBBFGOMA0Y3F", "api_token" => "7LMImFR26wUnrzTlpsmrlfd3CTjoQqRj"],
"LYNGADGET" => ["api_key" => "CE-SJJVWDA0GEDOE7RO", "api_token" => "gUsb2znDckAJgJxbzTja9PenFIGZiMXJ"],
"KOKO303 - [HAAACAA]" => ["api_key" => "-", "api_token" => "UG7"],
"Toko Sukses Abadi" => ["api_key" => "CE-O7WSTIUEYS0D0CA7", "api_token" => "Zs3HNzVkMy7YMQjk4d13TQMul0LzN4Ag"],
"DS Seluler" => ["api_key" => "CE-CYFNEYN15PXXFQLL", "api_token" => "pmN6YCI7pUvgpvPMBdMCOoLKB2XqO3nD"],
"SPMART" => ["api_key" => "CE-QLFU5QTEMRARYAMX", "api_token" => "HDeVCZGiv77WET1bDgNwqyWDlhiAWguB"],
"LimaLimaSHOP" => ["api_key" => "CE-HDK72WEXYCKDFC4O", "api_token" => "mRD65182OQn1pGontdlYDwUCIfMwtyO7"],
"MN" => ["api_key" => "GADGET", "api_token" => "CE"],
"DJ" => ["api_key" => "GADGET", "api_token" => "CE"],
"DJ" => ["api_key" => "MART", "api_token" => "CE"],
"Optik Cahaya" => ["api_key" => "CE-WAI2PTOCGYJP0VLK", "api_token" => "RZSjLTmgwBBm004TXcFlzUDQXSV9Rbag"],
"ZONA" => ["api_key" => "NYAMAN", "api_token" => "MART"],
"KACANG" => ["api_key" => "MART", "api_token" => "CE"],
"DRAGON" => ["api_key" => "MART", "api_token" => "CE"],
"DE" => ["api_key" => "GO", "api_token" => "PEK"],
"KA" => ["api_key" => "CHIT", "api_token" => "CHIT"],
"KERA" => ["api_key" => "MART", "api_token" => "CE"],
"AMAN" => ["api_key" => "SENTOSA", "api_token" => "MART"],
"AYO" => ["api_key" => "KREASI", "api_token" => "MART"],
"DEWA" => ["api_key" => "MART", "api_token" => "CE"],
"DETIK" => ["api_key" => "NEW", "api_token" => "MART"],
"AGEN" => ["api_key" => "DEPOT", "api_token" => "PLUS"],
"AGEN" => ["api_key" => "DEPOT", "api_token" => "AIR"],
"PULSA" => ["api_key" => "BERJAYA", "api_token" => "CE"],
"Bonz" => ["api_key" => "CE-IGQ6WF2NNXONXKM0", "api_token" => "NzvVISV58ByvFKByqKj278iP9OXEwz3v"],
"HOKI" => ["api_key" => "MART", "api_token" => "CE"],
"DE" => ["api_key" => "GOCHENG", "api_token" => "MART"],
"IT" => ["api_key" => "PEK", "api_token" => "PEK"],
"GEGE" => ["api_key" => "MART", "api_token" => "CE"],
"PEK" => ["api_key" => "PEK", "api_token" => "DE"],
"TOPANBET" => ["api_key" => "-", "api_token" => "BACADAB"],
"HADES88SHOP" => ["api_key" => "CE-LMW130PY4LWTRL1A", "api_token" => "loNFrOMdvss9RajArOfY4bnjXpPQpPZl"],
"LATARSHOP" => ["api_key" => "CE-IXH6NVYS5RPXYT6L", "api_token" => "Uv7OJ46Xqrc7AbHT7Ixm11shB3V8IsCG"],
"Voucher dewa" => ["api_key" => "CE-PAALFYORWLFGBY0J", "api_token" => "FeAMJzuzfIjt4paYGVPWbj4U3QDJniKg"],
"Andorevaldi" => ["api_key" => "CE-MFK7VHYVTU5LUORG", "api_token" => "8czZfUfZcK0VwQT19lcacRRfp6xyrkB2"],
"CRONOS" => ["api_key" => "UNOSLOT", "api_token" => "CE"],
"CRONOS" => ["api_key" => "UNOSLOT", "api_token" => "CE"],
"EXCELLENT" => ["api_key" => "SHOP", "api_token" => "CE"],
"RM Bersama" => ["api_key" => "77", "api_token" => "CE"],
"Mpay (inactive)" => ["api_key" => "CE-PMH5TNIWP7DP1SYY", "api_token" => "bDoJuPHz0sytlAxvqBtp5seNZmWiORbQ"],
"Mpay" => ["api_key" => "CE-SZWFR70N1IWEUZIL", "api_token" => "1U9rFJS93qttufKSkxqC5UhwB6keB6XK"],
"RM Nusantara" => ["api_key" => "77", "api_token" => "CE"],
"FORTUN365 [1ABIGAD]" => ["api_key" => "-", "api_token" => "GIGA2"],
"GB Shop" => ["api_key" => "CE-A8VPCIN58PXJ4CEJ", "api_token" => "Xdm3jU3JPqrO4XEdC8oEUG6FZWjx7kZ6"],
"DUTA" => ["api_key" => "PONSEL", "api_token" => "CE"],
"RAINBOW" => ["api_key" => "STORE", "api_token" => "CE"],
"SKYLIGHT" => ["api_key" => "GADGET", "api_token" => "CE"],
"HALO" => ["api_key" => "CE-MXYPRNI5OUT0PRC5", "api_token" => "QrPcUpGpy8zmtwuxusaIVTNzvn9KBNrc"],
"SOQ" => ["api_key" => "CE-KTLDUS5RSOKV0YPT", "api_token" => "Ts5RY26kiVNzaV3PR9IGSM2irDOKrfzO"],
"JET" => ["api_key" => "CE-Z0CGYAPO7GHRMSNR", "api_token" => "JOZUDbliPj2Tpli6upCbPGJp5SPcgdEf"],
"B13" => ["api_key" => "CE-26D5WL4REYDRYEBJ", "api_token" => "std98JKBhbAr1SbgHH6o3WmOeNNu1Pwy"],
"SPV" => ["api_key" => "HALO", "api_token" => "CE"],
"CLEAN" => ["api_key" => "CE-JJ3QDUQKJVYIM2F8", "api_token" => "E1GxQAf6Lcy4PukVucYjCkCj5LTSwUZB"],
"v1001" => ["api_key" => "CE-UCXV7KR5Q2WAQCLM", "api_token" => "pUb0seAWL4yzT3fwcqvFRbpUPWzvFEW8"],
"Florist Mart" => ["api_key" => "CE-W79I8D7NDJEVDRVN", "api_token" => "L1kg90qsuLrfB1Y33kBTftwlkmGP1kY6"],
"RANI" => ["api_key" => "BAKERY", "api_token" => "CE"],
"TAMPUNGAN" => ["api_key" => "URGENT", "api_token" => "CE"],
"RICKY" => ["api_key" => "CE-VCGEDCSAUDHWLBIF", "api_token" => "qECEQUKa6ItSlkuEWOEphCvss2XRtSTd"],
"ADMIN" => ["api_key" => "CE-C2CT9PUTL15MQ0G7", "api_token" => "rjgyRLFJrDz97EtNoV6TZk3NmJ6RUEAo"],
"RJS" => ["api_key" => "CE-HQOHMPSL20JIJHGD", "api_token" => "gurzN98FZ5QMIUt6v2uB4qIz6WoB7m2s"],
"AIRTOYS" => ["api_key" => "STORE", "api_token" => "CE"],
"KORAN" => ["api_key" => "DETIK", "api_token" => "CE"],
"Kopi Susu Alami" => ["api_key" => "CE-IL6YJY1BMMAZBSMB", "api_token" => "WGJeaBpaPW1Ro6F33bxZc9855bHwEJDM"],
"snack food" => ["api_key" => "CE-LJTQKJJT54HQTDMO", "api_token" => "SkEZi3tsyRY0jKCRBkh8bdRZCE6hfFJI"],
"LDR" => ["api_key" => "CE-W4DFVS9LGU9WYYFD", "api_token" => "WV5kx3BL7MUR7gAF0TKW8OYtTjv1S2gw"],
"THONO" => ["api_key" => "CE-LYROA3PQQDBOA2PV", "api_token" => "ORpR8SlDyuTEyF4tV1Djxfq6nAnAZRgC"],
"ITBITB" => ["api_key" => "CE-PLQTYXWBOH8UGHJR", "api_token" => "dLTsAZAWG6sX5GfjqsV5qoUINpuvSHcM"],
"FLUSH" => ["api_key" => "CE-YGBYZHUAOGU8J19A", "api_token" => "hAD5ejy3nJLjNicae2HGmVDS5ToSEMiv"],
"Sukses tiga tiga" => ["api_key" => "CE-0DYGSKRJUM4O3WQY", "api_token" => "BegxMlxVlkvehVZ7XSROeuWrEpZpsmjN"],
"WIKI" => ["api_key" => "GADGET", "api_token" => "CE"],
"TIGA" => ["api_key" => "SAMUDERA", "api_token" => "CE"],
"admin2" => ["api_key" => "CE-2RLLERCGQCKDG6VW", "api_token" => "yE6R3hQ70Uocozwf5uKftoChI8LHRAxQ"],
"DUU" => ["api_key" => "CE-FTYW36JA55OTKSBK", "api_token" => "7Smx4P7RH9sfDhAIwlqLM8q3qFwptUQL"],
"LDRY" => ["api_key" => "CE-KPC2QVRY4SMSLPCT", "api_token" => "8295qMZj9EiVo2iVR3O5EyW0qXq26tyT"],
"MEGA168" => ["api_key" => "CE-S0H7ORHJZOVL2ZS4", "api_token" => "jABfbAMnWwmDsohmInvcgW8lPf4BSWSA"],
"Jona Store (inactive)" => ["api_key" => "CE-MQH0RZVI1WHOIQMG", "api_token" => "bnKIPblNAeQValxZcgtWvCXVrVpoovvt"],
"HWUTAMA" => ["api_key" => "CE-J0OXCANQZWUYNMHD", "api_token" => "3umOlZxPNxaVv322Y4638RkyjWDETsNR"],
"HWHENG2" => ["api_key" => "CE-FZHJNU61MGGLEGR0", "api_token" => "sRPNXR5UJI274jjMmJsJfPABT56pNcw2"],
"PPKM" => ["api_key" => "CE-TMGXENEYSYKTYC4G", "api_token" => "sRn6xjVEHRIPFrmqt64F7x7WNCtnzPQv"],
"GGWP" => ["api_key" => "CE-FV1C66BNRLOIQE3V", "api_token" => "jUPItnd69ltSjU0ZqQuvxqXVuMKUBmDa"],
"BGS" => ["api_key" => "CE-U7FGP4NXGQMXXAXS", "api_token" => "XovoasaDbCuKMmLiZBLolK59tuZh8C7y"],
"NAGEMIL" => ["api_key" => "CE-J8ZSOKL41BM2ZBTA", "api_token" => "BrRV2Z310qpds8rWH7yQJbn4g9JePry2"],
"ITB" => ["api_key" => "CE-L0OEQYFH1NGONKUY", "api_token" => "xwugelqKiYFiQx7Zlu6LBd7aGK6zXTDv"],
"AJMC" => ["api_key" => "CE-WUDWGR6GMBNS1LL7", "api_token" => "gTPqMN7BYW2UkZV4hRBBXs9I53JgPbmb"],
"KONGSILANG22" => ["api_key" => "CE-6R38QEIIBEE3TW0J", "api_token" => "eXSHKaX2jj75CKxHAJJ4C1OjSHVTn1qW"],
"S89" => ["api_key" => "CE-LN4HK6IWKBQQGW4V", "api_token" => "ceaeEQeWhVNUVrvbKp7rKsvt38PwbJVK"],
"BNS" => ["api_key" => "CE-RXQMPSRC7S853XU8", "api_token" => "R9L4NSs0daNV3Lvq8uZelX7mppxbRm5A"],
"FFS" => ["api_key" => "CE-54ZSYZ21EHZ0N8ZD", "api_token" => "9F9xeZ8HeYCenNQP9jYhzBVjX9fjVaiw"],
"P2M" => ["api_key" => "CE-YCVMDE855NXNAWQE", "api_token" => "zwJGRCqyC1NuFJmsp8U3DnYwSKZWEeGr"],
"SCW" => ["api_key" => "CE-TXPSZCEOUPDXGVX8", "api_token" => "9zcaVJ6F7q1y9AMihN3cJacklU4GYrOt"],
"SCW88" => ["api_key" => "CE-0TCCHABK02WVI1SN", "api_token" => "VL73zrn55cHF12vAznJTSnvZyTMBS5vT"],
"SCW77" => ["api_key" => "CE-NTJZ1WJPBFZ1WYWD", "api_token" => "ehtdp1iNhGB0PLDvmrW0xC7rgOQYS2E5"],
"SCP" => ["api_key" => "CE-VEF5DPBDK4YVJ7AQ", "api_token" => "9LOQqN0flvNrv9TIh4IBKGJ54GxKmALJ"],
"LEADER" => ["api_key" => "LOCAL", "api_token" => "D1"],
"Jona Store" => ["api_key" => "CE-QNQS6QIHXZPSIDFQ", "api_token" => "V65YZiEfOxTvUeO97vMixiJ7UM0myvdE"],
"Sultan Mart" => ["api_key" => "CE-HEGDQL089BRJZWGF", "api_token" => "NLo3gqCm2jt1hgAbfKTJ2cs5fa3UNaLM"],
"Suhu Mart" => ["api_key" => "CE-VZK1UVFVRCHT9WZ1", "api_token" => "OxSkv9gJ5aMktXNSR5pYKI1VyN4YAKvL"],
"Net Shop" => ["api_key" => "CE-Z2TV3AQ7VDA6BX0S", "api_token" => "GaRoK1u1PGXWUlRadmjsgwf5VQvFaCne"],
"Cerah Mart" => ["api_key" => "CE-QOVYN876IJW0RK1F", "api_token" => "szGj2ZWK5i0yO7MpXLOngN6JpNm42d0D"],
"SALARY" => ["api_key" => "CE-WYJMIK9I6P2DR47H", "api_token" => "L7nfDn6oqwhtR5pZpj12VOFh0EYGFiI4"],
"Zoom" => ["api_key" => "CE-GW9A9YFDRCE4PCPE", "api_token" => "zkFXrGaD6RuTb7Y2n6bh5LZ8PUqSUReT"],
"HALO" => ["api_key" => "GLOBAL", "api_token" => "PRATAMA"],
"TOEDJOE" => ["api_key" => "TOEDJOE", "api_token" => "GROUP"],
"KAS" => ["api_key" => "LAPANGAN", "api_token" => "SGC"],
"SELALU" => ["api_key" => "SENANG", "api_token" => "CE"],
"PT" => ["api_key" => "BESI", "api_token" => "MEDURO"],
"SUMBER" => ["api_key" => "MOTOR", "api_token" => "MAJU"],
"RODA" => ["api_key" => "MOJO", "api_token" => "SENTOSA"],
"HAPPY" => ["api_key" => "GROUP", "api_token" => "CE"],
"WARGA" => ["api_key" => "CUAN", "api_token" => "BERSAMA"],
"PUTRA" => ["api_key" => "SUKSES", "api_token" => "SELALU"],
"MANDIRI" => ["api_key" => "PUTRA", "api_token" => "SELALU"],
"AGUNG" => ["api_key" => "MANDIRI", "api_token" => "PUTRA"],
"MAJU" => ["api_key" => "MAKMUR", "api_token" => "CE"],
"SURYA" => ["api_key" => "MAJU", "api_token" => "KENCANA"],
"JURAGAN" => ["api_key" => "MEGA", "api_token" => "JAYA"],
"SUKSES" => ["api_key" => "TECH", "api_token" => "ABADI"],
"SETIA" => ["api_key" => "ABADI", "api_token" => "NANJAYA"],
"DESIGN" => ["api_key" => "OOTD", "api_token" => "CE"],
"PT" => ["api_key" => "NAGA", "api_token" => "MENEMBUS"],
"SK" => ["api_key" => "PRODUCTION", "api_token" => "CE"],
"MAJU" => ["api_key" => "SELALU", "api_token" => "USAHA"],
"KOORANG" => ["api_key" => "KREATIF", "api_token" => "CE"],
"willy" => ["api_key" => "CE-PUBWTMUH7EWZECLK", "api_token" => "RMzklgCpAsusYGWfWVMhsM0UlCCj2Zb0"],
"BEBAS" => ["api_key" => "SOLUTION", "api_token" => "CE"],
"JAYA" => ["api_key" => "SEMESTA", "api_token" => "ABADI"],
"SELALU" => ["api_key" => "ABADI", "api_token" => "CE"],
"PT" => ["api_key" => "HALO", "api_token" => "GOOD"],
"merchant-3-prd" => ["api_key" => "CE-OLFTC1TYTT7RJDKK", "api_token" => "bwCPPxf50igPzvBdbnwrjBBq3nJiOVjc"],
"merchant-4-prd" => ["api_key" => "CE-UIRF5SJQRVMLW7F9", "api_token" => "ZjjZWKNwwxL60NKjlZP7y9B59seW6jkp"],
"merchant-5-prd" => ["api_key" => "CE-AUXZLDVV8P7YLKYR", "api_token" => "sVceO7We2USdD0rHwXAyUjLWrKtGqofv"],
"BERSAMA" => ["api_key" => "NAGA", "api_token" => "KEMBAR"],
"SEMUA" => ["api_key" => "INDAH", "api_token" => "PADA"],
"PT" => ["api_key" => "ABADI", "api_token" => "JAYA"],
"PT" => ["api_key" => "TAHAN", "api_token" => "KAWAN"],
"MOMO" => ["api_key" => "GATSU", "api_token" => "CE"],
"PASTI" => ["api_key" => "SUKSES", "api_token" => "BERSAMA"],
"PASTI" => ["api_key" => "SUKSES", "api_token" => "BERGABUNG"],
"TJAP" => ["api_key" => "NETWORK", "api_token" => "CE"],
"PT" => ["api_key" => "SEBAJA", "api_token" => "CE"],
"PT" => ["api_key" => "SUKSES", "api_token" => "ABADI"],
"GUNTUR" => ["api_key" => "PERKASA", "api_token" => "CE"],
"MATA" => ["api_key" => "ABADI", "api_token" => "CE"],
"KARYA" => ["api_key" => "DELAPAN", "api_token" => "CE"],
"v1019" => ["api_key" => "CE-DC4TFNP165NDAZZY", "api_token" => "YbfRIDPDmmF1rvopY40CwlDAyTq5HM5X"],
"v1034" => ["api_key" => "CE-AXZS7YHNXYZQMV2R", "api_token" => "wNGvSdrq4kfBWkNvq9QIftLyE0I38FLj"],
"v1057" => ["api_key" => "CE-CWDEA9S4PKOHE8EM", "api_token" => "DLHUnaYpHekmWq262xYzdUrgPnw5z4XB"],
"SPV" => ["api_key" => "VC", "api_token" => "CE"],
"VKN" => ["api_key" => "CE-JEN9RPBRGJCJOMCY", "api_token" => "9p76k5db2isE5FdBCLFpS9gVRM3KlStt"],
"v1046" => ["api_key" => "CE-7COOEQEYJ4PTSRPY", "api_token" => "9BltM7CRwvNEqsWWuaTdVmZJt3BWn5N7"],
"Toko Bagus" => ["api_key" => "CE-S8PF5BOI094BJCZ3", "api_token" => "MDq1bJ7S4nw1Uqk9DepzRXLcg8XgCE3s"],
"Zenpay Gaming" => ["api_key" => "CE-DVMLNDQZEQLGIOM5", "api_token" => "FQPrvzS9zwmK3F9vwNaqhWNWEfCkPtEe"],
"Paid" => ["api_key" => "INQUIRY", "api_token" => "CE"],
"SQGQ" => ["api_key" => "CE-YRIUSPPQ9HLKM39W", "api_token" => "cJjPEvs3VbK3Zq7GUutFjBbig1uToKt6"],
"Bezita" => ["api_key" => "CE-CSYC8QAJO5NG9NF6", "api_token" => "oNsRaGjOKr7y6zntRs2LmRKR8jSHAqRA"],
"TOKO" => ["api_key" => "TIDAK", "api_token" => "BAGUS"],
"oconggaming" => ["api_key" => "CE-IBI3P6QDZLP7JYST", "api_token" => "WTB6HfCfBtyn0FkKVYg4Z0fXxLOYyTap"],
"ucok" => ["api_key" => "CE-Q2Z6OHDYFCXZWTLE", "api_token" => "tkZw6TKHjMtKMI0bpAkXjwWFOMAotaM8"],
"wan kenn" => ["api_key" => "CE-PGOYKCAQPESLIGHS", "api_token" => "Fje8WO2wsDmXxDdl5AngBGL9hWQOeGA4"],
"v0057" => ["api_key" => "CE-WBHGIQPXUPSQ9XRN", "api_token" => "PW8bmK5Bpm2X1VllCQuJFzazEY8BYOHC"],
"v0034" => ["api_key" => "CE-EHYBS2GSNJD8VENX", "api_token" => "AzEZ382gYLlTEy0aj0SkDx0KaO5sYCN4"],
"v0019" => ["api_key" => "CE-7B6S41E76YR8V3AG", "api_token" => "JoCmaOdp9aBLAcgvYDckxKgfj4KmuRZn"],
"Zenpay88" => ["api_key" => "CE-UFLERAQXWSTESBCY", "api_token" => "c6W6K1f9GZI7RcVoh4I4sGgTxnxykw0T"],
"HALOJP" => ["api_key" => "CE-MYTODBMTRJOZMTPU", "api_token" => "EcTSYI0yyJxf6Q2pif6Ud9xBtlCKOmg5"],
"SPV" => ["api_key" => "HALOJP", "api_token" => "CE"],
"SPV" => ["api_key" => "SQGQ", "api_token" => "CE"],
"seo_boy" => ["api_key" => "CE-6ES1FE9JTYXRGN7K", "api_token" => "8UWOSMzisu7E0SfS0jZ4Kg6t5qwIp6ni"],
"Selamat" => ["api_key" => "T", "api_token" => "CE"],
"Cerita" => ["api_key" => "CE-GCIMNEKXKY89LJCF", "api_token" => "ql41ynFJWnI7QF3ydX1jRQKJLWLwKwIr"],
"Kawan" => ["api_key" => "CE-UT4OESMAEUGJBLKJ", "api_token" => "6DJHqesyjZfgIWJENZdO2mKiqt4mgVQ0"],
"Bintang" => ["api_key" => "CE-LTS9R9FGLXQC25J6", "api_token" => "XSQ6CcviW6ZPp3SVO4Djfa8uin8PJUIZ"],
"CBD" => ["api_key" => "M", "api_token" => "CE"],
"PRODUCT" => ["api_key" => "CE-7HRE8YQJ9E8ZTR26", "api_token" => "B0FrJKVt4vt0H4IUgX8errBpK1IK1NWE"],
"KIOSKAMU" => ["api_key" => "CE-XQQUNYT56FTZVE9D", "api_token" => "Aiivrf1sg4v24umpLyvrCz5pY6bYGSjB"],
"OLE999" => ["api_key" => "CE-5PAKS3YHYGUMYZVM", "api_token" => "Ve5elOSfAF312SlzP8UbfPW0JVyJ9AMb"],
"TOKOPEDIA" => ["api_key" => "CE-EQ7HMTZX4ALQQE7B", "api_token" => "W84GFSb1Bfm3G57oUY34PxfXQ7VwO7CN"],
"GIGA" => ["api_key" => "GAMING", "api_token" => "OHYE"],
"ZENPAY88" => ["api_key" => "CE-HCNQLJRIBSWQHT7O", "api_token" => "IeTyAO7JJGJu0W8URxOnkXHpmSzDOe6c"],
"jevency77" => ["api_key" => "CE-8X7MQH0D5VDOXTTD", "api_token" => "f30gjTg3n1gl24YDBUwDyaNhmR7JdJxY"],
"GIGA" => ["api_key" => "GAMING", "api_token" => "OHYE"],
"tampung demen" => ["api_key" => "CE-SOXRMNEZINM83KB9", "api_token" => "6dESy6fiVz0zQ3kqTZeAL60bUnAsa8PB"],
"F1" => ["api_key" => "CE-NRTZBVVNZIYPGA1R", "api_token" => "qaxgyQSTkT1RKEdaXS4ovG76nBycIB3T"],
"MPAY Group" => ["api_key" => "3", "api_token" => "CE"],
"hantu gaming" => ["api_key" => "CE-OX1BCPHUB712VRFG", "api_token" => "ZnkNG7qDSxONk9cifF9BIYP8hy2Xu4v6"],
"POUN" => ["api_key" => "FINANCE", "api_token" => "CE"],
"tour_guy" => ["api_key" => "CE-VITYKNJ2JZFSQT4J", "api_token" => "AGCspN0SF8KdTSLnOlPfkr9oIXXxK2AE"],
"Kring88" => ["api_key" => "CE-UAN7IJ1VMJOGY4TZ", "api_token" => "7cKrYbsjotNlWXYxSMGd2KQmCCWFk8Ob"],
"rajagacor (inactive)" => ["api_key" => "CE-LWNFBXOMBT4FHZQY", "api_token" => "ljmnngSiTObfSSZ4w5SyOdDC68C9gdi1"],
"rajagacor" => ["api_key" => "CE-TAFGK58ZWBCGEQVT", "api_token" => "Tp1o5rlFopESzJj6b4UVP81y5Zjot2Gp"],
"JJ" => ["api_key" => "CE-1P988TVKAZZMYGMI", "api_token" => "8qBRsGBkT8qDtjzW0ef2hojZHnMkqDO5"],
"Ranvnix" => ["api_key" => "CE-6MEGMWLLQDID38YQ", "api_token" => "2ufNu79rONdvbTOhy2cc2smlPpAeq6Ub"],
"FlushAUTOBOT" => ["api_key" => "CE-GPVEBBGKMWVSJC66", "api_token" => "lB42XqDrDkDLRggfgI4QoOVXMjArvAHk"],
"mama muda" => ["api_key" => "CE-GOLPSKVAWVSHSVNC", "api_token" => "aZEmA1Lgv7L6rVlwn4OmUbOK6Fz1Hrh4"],
"sultan tampung" => ["api_key" => "CE-WHBQNA6SLZGZ1YIJ", "api_token" => "UXAg7l4UrAgamq1AOfNT3BwZGiNtcAK1"],
"Cokelat Shop" => ["api_key" => "CE-FSO111X8I4JO3CWI", "api_token" => "BObdLQtHYcK2PABAMKoA9HcFOcBKwSdw"],
"Lapaku" => ["api_key" => "CE-0NFJ60IRZFWXWBXS", "api_token" => "EqkN0BhxTvWE31LORdIyARpaxIWaBCCh"],
"SINGA" => ["api_key" => "TOPUP", "api_token" => "GAMING"],
"SEMESTA" => ["api_key" => "PULSA", "api_token" => "CE"],
"SPAREPART" => ["api_key" => "THAI", "api_token" => "SHOP"],
"lapaku" => ["api_key" => "CE-9FEWIBQMDQQIB1JS", "api_token" => "Cx2XHckcTVB8DmE5JkjosdehI3y3IjQH"],
"SPAREPART" => ["api_key" => "THAI", "api_token" => "SHOP"],
"MACAN" => ["api_key" => "TOPUP", "api_token" => "GAMING"],
"Mpay" => ["api_key" => "2", "api_token" => "CE"],
"TUMI" => ["api_key" => "STORE", "api_token" => "CE"],
"Cahaya Inspirasi Shop" => ["api_key" => "CE-WIQNZHVOVHQ76LEY", "api_token" => "LoTQJJfP5oFceBd5LRRWU0swK3RUPyQP"],
"CIPITMART" => ["api_key" => "CE-P4HEQ7TIAGQXKQ3T", "api_token" => "ymyINWQoh8bQhJIL4WZ31uVGX9ll2JfI"],
"TUNAS" => ["api_key" => "PULSA", "api_token" => "CE"],
"MACAN" => ["api_key" => "TOPUP", "api_token" => "GAMING"],
"TokoMonas99" => ["api_key" => "CE-JZHZ7UZKHVPMD9G5", "api_token" => "VWRWRcmbo7xBJ2cd7UmiQrhts61ToKuU"],
"SEVELMART" => ["api_key" => "CE-KGS5SQQC7JKOHPKT", "api_token" => "zferLl6o4UiyBK4KIWWyvTOqCI7Y8eR4"],
"J20" => ["api_key" => "CE-KOVDTAFWCF8BLBCR", "api_token" => "1imWGxeEa7XdKbYorHkSsznuJodprfGV"],
"39tampung" => ["api_key" => "CE-N0FQFCGUNDJLLVDK", "api_token" => "RfpEg4f49eLr1uIqbl8qTdnKYg40H9qk"],
"BANKBOT" => ["api_key" => "CE-RXK7GQSKEOZDFZKX", "api_token" => "vd80ncz5R9XB17edAGCpFOVVDjT93T4t"],
"Star Shop" => ["api_key" => "CE-ORSGQZDZSEWSEFFH", "api_token" => "EujtSfN9XgkhuPyr7W09kRhRu36RxXEa"],
"Viking" => ["api_key" => "T", "api_token" => "CE"],
"LASARA" => ["api_key" => "TOP", "api_token" => "UP"],
"Instan Penampung" => ["api_key" => "CE-HD75BBQ3JIBU4TLE", "api_token" => "nIuKZ1mbwx85TTd5Gbyj05tPPzpENbwV"],
"Es Mart" => ["api_key" => "CE-OPRS29FFJMDGKAOP", "api_token" => "bxbf0fFJn5WUmxkJqxzWsEeJmDZCvX6s"],
"blackhole" => ["api_key" => "CE-TZKCETNRS9VVNI2B", "api_token" => "IFHBnowhterV6Le2gm31cXPWwKO97IAA"],
"cheetah" => ["api_key" => "CE-5JQFQTMWOJ6OZERN", "api_token" => "6VhZp7pddyhIdMEa4zS9ii0tmHQo4f5N"],
"BERKAH" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"eightynine" => ["api_key" => "CE-B5EM3YBY8EN6PSGJ", "api_token" => "PgHJcDqJMPf7NR2s08OevYvcqi3O4rWK"],
"Bonusan6bulan" => ["api_key" => "CE-NALEQPX4OG1GRTOL", "api_token" => "GDfYdCBShTkmNV1hb7kQI6frEkjZFZbx"],
"Terbang" => ["api_key" => "CE-Y05LOJSWPNFL2PKX", "api_token" => "Ec95vpNNM5FxtkIouJzQiiLoSlnPOfMx"],
"FENDI" => ["api_key" => "SHOP", "api_token" => "CE"],
"Kenzo Shop" => ["api_key" => "CE-8JXXNG2SHVJUC473", "api_token" => "PX0OK8rUWuStpaH45Uo8iEe9ru4hhLLT"],
"HULK" => ["api_key" => "TOYS", "api_token" => "SHOP"],
"KAKAP" => ["api_key" => "SHOP", "api_token" => "CE"],
"JAGO" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"GAJI OKT" => ["api_key" => "-", "api_token" => "NOV"],
"nyam2" => ["api_key" => "CE-UYV3B9N33SIYXFN6", "api_token" => "M8U2bgSzV23VrfBKzzF6nuZrBsPamKu4"],
"SGCVIP" => ["api_key" => "STORE", "api_token" => "CE"],
"Talenta" => ["api_key" => "CE-7ENCJEGXVRNVVFLI", "api_token" => "w1b0T3EsNVLHELdVcGHKKKyOIglRblK3"],
"Personal" => ["api_key" => "CE-QPFGMJEZAEBSD8EX", "api_token" => "dCznP4Wd1RUmIwWFpcEqx1K24q9hCzeh"],
"Igames" => ["api_key" => "CE-RNQELFPKEQ1HOM4B", "api_token" => "lxnJkXjS6yrYHDoBBNpcFwM5u2Y2ckpN"],
"Hadir69" => ["api_key" => "CE-0WFWBAXZLDDIWVY6", "api_token" => "pPYK6HFM47ePjlQ1wA6upfZQPdZVKQDU"],
"Agen118" => ["api_key" => "CE-BKUKOSKGA4GYJSGT", "api_token" => "Jk1ukX3W3uynhqW3nqradN5ojiZdNNbb"],
"MEGA" => ["api_key" => "MART", "api_token" => "CE"],
"NETWIN" => ["api_key" => "SHOP", "api_token" => "CE"],
"LALALAND" => ["api_key" => "STORE", "api_token" => "CE"],
"NTT" => ["api_key" => "CE-OYNZHDNTAFFB1UBP", "api_token" => "JAsv1IOKoAlmZphHCV7uWubtFJ11GoRi"],
"MASTERTOPUP" => ["api_key" => "CE-J1D686FTTLYPGQPD", "api_token" => "ebO3ZGwgVymvulefbWwFB0a3bi33r5YQ"],
"INDO" => ["api_key" => "KIOSKITA", "api_token" => "CE"],
"KASWARI" => ["api_key" => "SHOP", "api_token" => "CE"],
"Merpati Shop" => ["api_key" => "CE-FIIODOLJ8KOGNLY5", "api_token" => "FnjCB8XyxxViTvdZdWgqPHUGlWsD9jA1"],
"Wolf Parent Project" => ["api_key" => "CE-QILA0CNYD6QVBMIY", "api_token" => "0lpikHvjtS8DiSOORvx7pTmoPxkeRWLz"],
"SENTRA" => ["api_key" => "GADGET", "api_token" => "CE"],
"Mpay" => ["api_key" => "1", "api_token" => "CE"],
"MNA" => ["api_key" => "CE-XFVI25JER8NCOIUC", "api_token" => "WcCRlCQGl7b7aMvAaGEtz71ROEIQwwo5"],
"MEGACOR" => ["api_key" => "AUTO", "api_token" => "CE"],
"SIP" => ["api_key" => "STORE", "api_token" => "CE"],
"API" => ["api_key" => "MART", "api_token" => "CE"],
"API" => ["api_key" => "GADGET", "api_token" => "CE"],
"API" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"API" => ["api_key" => "SHOP", "api_token" => "CE"],
"SARANG" => ["api_key" => "BURUNG", "api_token" => "CE"],
"TOKO" => ["api_key" => "TRIPLEK", "api_token" => "CE"],
"TOKO" => ["api_key" => "KARPET", "api_token" => "PERMADANI"],
"Sel Darah Muda" => ["api_key" => "CE-ENUACRQHDCROTUQH", "api_token" => "5DONbfwhYlnj9HT2YjUTA3ihxZrSOYgy"],
"GG_OPS" => ["api_key" => "CE-U36SCXFIKPNKFRW1", "api_token" => "aJksy6Gx65aAAdHKrhueJEk5aCtzJm7f"],
"TOKO" => ["api_key" => "SARANG", "api_token" => "BURUNG"],
"SARANG" => ["api_key" => "BURUNG", "api_token" => "SEJAHTERA"],
"PANEN" => ["api_key" => "MART", "api_token" => "CE"],
"SUPERKING" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"SABA" => ["api_key" => "MART", "api_token" => "CE"],
"PANEN" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"DUNIA" => ["api_key" => "SHOP", "api_token" => "CE"],
"tampungbaka" => ["api_key" => "CE-017XE1VRJ4OMGMZ9", "api_token" => "jREdmmgbxYEOOpy9Mmg3DQCdCXikGTDS"],
"TOKO" => ["api_key" => "TINTA", "api_token" => "MAKMUR"],
"TINTA" => ["api_key" => "MAJU", "api_token" => "CE"],
"Kiranaecom" => ["api_key" => "CE-IVKCW86YFV94NMY6", "api_token" => "TUBxWF6kojQABlr5Onwtl5SNufKAOvhs"],
"bhavanagame" => ["api_key" => "CE-LYMIS6EFITGTJTN7", "api_token" => "Dcl9VWdtsMGNAB9qzGb3rYSaLGfX6N13"],
"MMKecom" => ["api_key" => "CE-GO0KNHH2QXMELAJ5", "api_token" => "7oIYegLQGGIPmtKwCeCplmHtbOStPJkq"],
"Arkatamaecom" => ["api_key" => "CE-UIPPORXAAXARNQTS", "api_token" => "ytLiuhrfxvMVwM91LswVMG9aq4yTJa7q"],
"Ghanimtek" => ["api_key" => "CE-VDNTJOZTDR1PGEPW", "api_token" => "rFbRSad9eYXRzD6JPagPyiUgto3rYo3A"],
"Bimatek" => ["api_key" => "CE-NJ3EV81S4KQ2ZCQL", "api_token" => "QDZ1wpBGafwHNxvZ0swej3yRMB9yXsFT"],
"AnagaTek" => ["api_key" => "CE-G8MCSOZ7MFXUJKZB", "api_token" => "djilmv19ThJPjfA44TOtizT61uoXU8zu"],
"Abhitahecom" => ["api_key" => "CE-2ELHMRHD5W9HXXU7", "api_token" => "cR9myctn4J4Fg0nL1xaasL5kxrtldPIp"],
"Tunggalecom" => ["api_key" => "CE-NLCACJ7QEPVFDQHG", "api_token" => "W8sB50OEk2WEPmDvQ3m9yttbwtMiaDuG"],
"Bintangtekno" => ["api_key" => "CE-FPLUAOIXZ9SMUBXV", "api_token" => "K5o0Ps7YN3uqdNzwiD4oJlZbJuW8eVc6"],
"Aryaprimeecom" => ["api_key" => "CE-O7SO9VRCFYUNXDPI", "api_token" => "yOyD5OK260WvOK1EemnNObJZUmdREFh3"],
"Andalanecom" => ["api_key" => "CE-UWVPDA8VDTPS5JKW", "api_token" => "gFgjGisJq8BeSjiW9KUU1K1djLTzvbIQ"],
"Ourtopupecom" => ["api_key" => "CE-PWW5HY9ZWIDITPRY", "api_token" => "rd5xB7JZRwluMWSBmjI6JyYOtH0LBjZl"],
"Bangunabadiecom" => ["api_key" => "CE-COCXEDT4UFFDHKPP", "api_token" => "qb499JrGyXZ4YiZAYZCB7to4MwGd1VUX"],
"Paramaecom" => ["api_key" => "CE-HQ0MRXINHHPYBDBY", "api_token" => "Ct3riJe30TJVciyPJbUVOwCg2rH6tFOa"],
"Sinar Keduang" => ["api_key" => "CE-JVKJU0C2TJVJSIGI", "api_token" => "3vJ3p4hDmyLKYxKACXH6PkkusJUGofWT"],
"Khusus_denda" => ["api_key" => "CE-MBDHGZJMVOUS9PVQ", "api_token" => "6tNZkqAO8EKnaUE3GiO5pdXnXMi6tqnk"],
"hailee steinfinalen" => ["api_key" => "CE-CKPU0CIHHBAHUBRO", "api_token" => "v7sZKSlTmLpy4T67c3D9CTmPlaFosyLV"],
"V1069" => ["api_key" => "CE-CDUBPTMWW1JKHASW", "api_token" => "2tcgi7ZwElwuhE00DUwUYjD5Wb7q5Sb0"],
"SURIA" => ["api_key" => "SHOP", "api_token" => "CE"],
"PAPA" => ["api_key" => "MART", "api_token" => "CE"],
"BIMA" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"Diamon Voucher" => ["api_key" => "CE-MMILVLPBNNCVLWEI", "api_token" => "zFV0yGLqxvZ4owVZljTi0tXibIJU1PwY"],
"snail" => ["api_key" => "CE-JF1KWWD1F51CHDAS", "api_token" => "65kCZSUNKbXSh0WAdD3ndAXb3RwmEHxd"],
"MT corp" => ["api_key" => "CE-4PVDCYBSDRWXRJUJ", "api_token" => "0PM4TpoQbXCcomIMACVIdD7Bf536GMXz"],
"Jenius" => ["api_key" => "CE-2AR1XMLUUYMCG3PR", "api_token" => "hlpblys8L5eGKwgJpbWl4z4snceeSw56"],
"Gajian" => ["api_key" => "MINDCONTENT", "api_token" => "CE"],
"RAHMI" => ["api_key" => "ANGGREK", "api_token" => "CE"],
"Wanda" => ["api_key" => "CE-JJL3IZX7EWG80EGM", "api_token" => "xy284HJwcjCvDtlhf8fpyf7G9YGwDGij"],
"progame" => ["api_key" => "CE-E2E2Z6CJ5U7CC7L2", "api_token" => "yW0xfTLwZbhvkaJmSSjEJZ4JysEf2lBY"],
"SWEET" => ["api_key" => "SHOP", "api_token" => "CE"],
"hengvivo" => ["api_key" => "CE-D8OFSOKHSB9QLOUW", "api_token" => "r0ea9zX5R0kZfwhzCMdePguFcw9P2LoH"],
"Fuji Gadget" => ["api_key" => "CE-OG6MVRR9TZ65IMNG", "api_token" => "rfS1OphurTcSZs5csmfyHN7K37z1FNnn"],
"ALGO" => ["api_key" => "CE-OX6GW51V3IYFX90N", "api_token" => "3AGVxytvo7k7TI7qWHB9jISu5y4d4N1N"],
"XTRA" => ["api_key" => "CE-01HRQMA752LZYPPT", "api_token" => "zg96AiJdtx4QE59DCAY4f2baOr0noLRZ"],
"FastPay88" => ["api_key" => "CE-3FJP3C0TRNPUCNEK", "api_token" => "QwMV7sjGJc7HFsKcZ0kZtn71hEF2fz15"],
"SurePay88" => ["api_key" => "CE-ZJPSQJQXTSI7HK5N", "api_token" => "bAnGnhp2FSHP1ljP3tl56Dejlc5d0qOc"],
"AsiaHoki Gadget" => ["api_key" => "CE-2N2ZXTF9I4FLSJ6F", "api_token" => "xRUZjQGHzW7Rjp73YR0GtPZJSLARMD27"],
"GACHA" => ["api_key" => "CE-ETCG14OSZGSEW2SE", "api_token" => "oA2lqApmw8VT2KEknNZ8pWWcmQhVGOlJ"],
"DEWI" => ["api_key" => "GAME", "api_token" => "STORE"],
"MULTI" => ["api_key" => "CELLULAR", "api_token" => "CE"],
"PREMIUM" => ["api_key" => "CELLULAR", "api_token" => "CE"],
"BEST" => ["api_key" => "CELLULAR", "api_token" => "CE"],
"OPPA" => ["api_key" => "CELLULAR", "api_token" => "CE"],
"V1072" => ["api_key" => "CE-QUBIEEGNRHGM2GDH", "api_token" => "LtSDVOphHXmEoZtCqbu4WVbpqDIOqymc"],
"V1070" => ["api_key" => "CE-OGZ6FCGBWVSGOZX5", "api_token" => "Rx5aTvYrCY1JKxq9mjE41KC3Ob69XXQf"],
"HIP" => ["api_key" => "HIP", "api_token" => "HORE"],
"Orin Flatley" => ["api_key" => "CE-OMWEHHXUZUGPEQWT", "api_token" => "igrfPUJj5Ond6CZ0DS4N5LQGF54J72xS"],
"Nettie Beer" => ["api_key" => "CE-BJYLFZVDLTX8XJMF", "api_token" => "ZeiBE61MYee0M7WLdTYRvQuGZl2fPabG"],
"X1gaming store" => ["api_key" => "CE-JOXH4WIDHBMY8N5A", "api_token" => "y0cOPtp7QtA3LbqTzS1Y6cqJZ6vjbUvv"],
"X1GAMING" => ["api_key" => "STOREE", "api_token" => "CE"],
"Vnix Mergency Fund" => ["api_key" => "CE-SPAR3KGTQCUVT029", "api_token" => "XBPAliFCdAP5ZBwXpMWMikAeUxNcKm6J"],
"LATO" => ["api_key" => "MART", "api_token" => "CE"],
"HAKA" => ["api_key" => "MART", "api_token" => "CE"],
"Project duakomalima" => ["api_key" => "CE-SGHQHVM1VLZPROAF", "api_token" => "q3eNsZoSNsdZ3PvPpUZOD0fWZbccw8ZI"],
"Edythe Hyatt" => ["api_key" => "CE-UFDWHBM1DDJMFE1J", "api_token" => "J9c711c3P0ygQnhZjch5DW2uVtxjp5L9"],
"SUPER33" => ["api_key" => "CE-N3FXTLLD0ITPTITP", "api_token" => "MDN581NcaQJOkW46RZ0pUnrczQ6Ik8Mo"],
"MURAH" => ["api_key" => "GADGET", "api_token" => "CE"],
"Hengamd" => ["api_key" => "CE-UO6WW2241UTTJMR7", "api_token" => "1k8s4Kdzk1D4hlbcRFchkfEobP89emql"],
"Wanda Upton" => ["api_key" => "II", "api_token" => "CE"],
"Mr. Oswaldo Conroy PhD" => ["api_key" => "CE-KRZLOGFANO1BYFNY", "api_token" => "5SwMVNOHWglcLXIwbEeWNiwGy8qeEPnc"],
"Project Autobot" => ["api_key" => "CE-L87ZO1LLW0R0NETD", "api_token" => "VTjfZcZ8Il2Tiyy5MDhMeI8Qws0siytk"],
"SK Pay" => ["api_key" => "CE-9TPMGJTINDGTPP5L", "api_token" => "6guRIn7Ot5M4cJCTe2CWI7fmp8tU3Jfd"],
"Michele Rutherford" => ["api_key" => "DVM", "api_token" => "CE"],
"Arely Littel" => ["api_key" => "CE-GJ3SEWIDPHXVWBZK", "api_token" => "r4Qaz7kMxo2FoaS4Km8z2pa23VEvQcjF"],
"Herbert Will Sr." => ["api_key" => "CE-KFMBKQZ1EDXFNIXJ", "api_token" => "2WofySaCtFecMv2ehujZJDRRJfxAjHMc"],
"Sigurd Batz" => ["api_key" => "III", "api_token" => "CE"],
"Carmen Bruen" => ["api_key" => "CE-SDKBJ3SEX9NFBWZK", "api_token" => "B4WlDYMLzZPqBFbR55Dl7D2uQ1U2OxMN"],
"Wiley Oberbrunner" => ["api_key" => "CE-2DCGLKLPME4BZOHS", "api_token" => "zO7JnafUPP6RYYRB6XUTcZlkT6uRIyqK"],
"Vnix Global Bonus" => ["api_key" => "CE-4WYNHHEMOLEGSNYY", "api_token" => "JUSzd6DCJHFQ3LJPmyJjUui0K4c93SZf"],
"Project Autobot" => ["api_key" => "69C", "api_token" => "CE"],
"Project AB" => ["api_key" => "-", "api_token" => "MEGA"],
"MAX88" => ["api_key" => "COUPON", "api_token" => "STORE"],
"ATHENA" => ["api_key" => "GAMING", "api_token" => "CE"],
"APOLLO" => ["api_key" => "GAMING", "api_token" => "CE"],
"CASPAR" => ["api_key" => "GAMING", "api_token" => "CE"],
"MORGAN" => ["api_key" => "GAMING", "api_token" => "CE"],
"WINSTON" => ["api_key" => "GAMING", "api_token" => "CE"],
"PICCOLO" => ["api_key" => "GAMING", "api_token" => "CE"],
"deletedcu8" => ["api_key" => "CE-JEUTNPE9MXTZS7GT", "api_token" => "cJoewK8K7s1B1PYLpHAUVqZu5Jp9LIEh"],
"deletedru8" => ["api_key" => "CE-QCWL7N65NTH5WYF1", "api_token" => "DNwlezhjM0AnNUncERASI2MDVhivBtRi"],
"SYRM" => ["api_key" => "CE-JRPGSNUKPZXTHABX", "api_token" => "LMmPfykUZHJIjZUFpVYzfEI6pgc5UCpC"],
"VOUCHERKU" => ["api_key" => "SHOP", "api_token" => "CE"],
"NOBITA" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"KINGS" => ["api_key" => "GADGET", "api_token" => "CE"],
"WIN" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"MEGAHOKI" => ["api_key" => "CE-0BNFIRGKBS8BB8OD", "api_token" => "LAhky2tJrfp7q7JLtf7ShcAF7Cs2ZQBT"],
"HAPPY" => ["api_key" => "CELLULAR", "api_token" => "CE"],
"OVO" => ["api_key" => "MARKET", "api_token" => "CE"],
"Happy Exclusive Batik" => ["api_key" => "CE-LFZRXTT5NUD6MSTU", "api_token" => "Xa81jy7tGJ1ekk5F3gxROs6Jf7qbyws6"],
"RAYA" => ["api_key" => "GAMING", "api_token" => "CE"],
"DEJI" => ["api_key" => "PEK", "api_token" => "MART"],
"J8" => ["api_key" => "CE-OACW5AQHEN61CERG", "api_token" => "dNrhq7E4ckVt85MUUoqkWj8J7whgyZAE"],
"PATIN" => ["api_key" => "SHOP", "api_token" => "CE"],
"LM mart" => ["api_key" => "CE-SUCI9EBZC5V15UUK", "api_token" => "uB0ZtwIclia2JGpUlJwsclXg6gNFNgAs"],
"DE" => ["api_key" => "JI", "api_token" => "PEK"],
"DEJI" => ["api_key" => "PEK", "api_token" => "PEK"],
"HL" => ["api_key" => "CE-0Z2L5TVV9KD8GJK5", "api_token" => "ViVIiuKkg8ShUzBDlLPMXIVuvy4yi7rU"],
"ACE" => ["api_key" => "HOLD", "api_token" => "CE"],
"KG" => ["api_key" => "CE-ULNQ4LEM7N7DSUTQ", "api_token" => "Lrjd6DW2ieIiG0aqVjapWpuju3RmYdgM"],
"7Cric India" => ["api_key" => "CE-DKRCAP8XTWWQEFHB", "api_token" => "jlvP8De5uiCiQLhxfdYnOfiYcFjD4X8n"],
"BIG" => ["api_key" => "W", "api_token" => "CE"],
"AYAM388" => ["api_key" => "CE-AWSIT4QFXSOCKW2J", "api_token" => "ZYvBebv0b1mbxcJ4yFECLTKFF85Fh6i7"],
"GD Mart" => ["api_key" => "CE-BKUXJVGFQ5QYQ4ON", "api_token" => "l1W3ZVS6w7aGcn6CNyxNf9tCNQUwx2vT"],
"PT" => ["api_key" => "HIP", "api_token" => "HIP"],
"DEN" => ["api_key" => "GAMING", "api_token" => "CE"],
"GIGA" => ["api_key" => "VOUCHER", "api_token" => "GAMING"],
"LUNA" => ["api_key" => "GAMING", "api_token" => "CE"],
"LUCKY" => ["api_key" => "MONapi_key", "api_token" => "CE"],
"GEMBIRA" => ["api_key" => "GAMING", "api_token" => "VOUCHER"],
"Daisy Dach" => ["api_key" => "MD", "api_token" => "CE"],
"Mercedes Effertz" => ["api_key" => "CE-DIHZF7GWYPQUUBOY", "api_token" => "IV3kg1QOjKhLu3UnNZt3Nc0hEoXHAXC9"],
"Ruby Shanahan" => ["api_key" => "IV", "api_token" => "CE"],
"Makenna Senger" => ["api_key" => "CE-O8TQKN40MLNKVWKF", "api_token" => "RSCducHU7Z3usRjmAeGsp5lmkctUwSLh"],
"Marcus Bosco" => ["api_key" => "CE-XVN7NXXFLKHCB3WR", "api_token" => "XdRBKrW6h5gjsm5TZCzDpUsXR3KABPTl"],
"Dr. Nicklaus Tremblay" => ["api_key" => "CE-SMML3QUKBK7ETAAX", "api_token" => "gosGlWU6khviXLnh21lfzloPN8koQZhZ"],
"Project AB" => ["api_key" => "-", "api_token" => "NUSA"],
"BARISTA" => ["api_key" => "SHOP", "api_token" => "CE"],
"LOTUS" => ["api_key" => "GAMING", "api_token" => "CE"],
"v1064" => ["api_key" => "CE-S5HFRP26ITU3TLOD", "api_token" => "5bBmTewhucHecOnHW4ev1mUMXEEltGBJ"],
"DUTA" => ["api_key" => "CELLULAR", "api_token" => "CE"],
"BINGO" => ["api_key" => "CE-FDBMJ3EXX1WOC3T8", "api_token" => "b0O64hl3lng0c4ktpjZxhjArNyCENf2i"],
"COCOA" => ["api_key" => "CE-5UVF4VQLSIMILPZ7", "api_token" => "K3julBxhxrmSe0YihmLx249e2OlaPZu1"],
"Project AB" => ["api_key" => "-", "api_token" => "GUNUNG"],
"SA7" => ["api_key" => "CE-NB2DBCJSVGYQ13DK", "api_token" => "dmw4TzOlYSvw1f6gBywZRc2t2uaX9Nrw"],
"TOKO" => ["api_key" => "ELEKTRONIK", "api_token" => "JAYA"],
"merchant-6-prd" => ["api_key" => "CE-AXLTZTRVG5EORGY1", "api_token" => "N7p7fOnw9KrhHoSsbmcOXLuCyWaCuo4N"],
"merchant-7-prd" => ["api_key" => "CE-I9OMJAITGQFFCF7Z", "api_token" => "ucVVvbjpqC8gROMfDj1vHjpCbW4BYrJR"],
"merchant-8-prd" => ["api_key" => "CE-EYVGLCY3VNCUTIFV", "api_token" => "V3HcoE7saIT9IBO6EBt5kCUFARRR21we"],
"merchant-9-prd" => ["api_key" => "CE-TGVSHXSUOGIPUTFK", "api_token" => "jeVFe3xbjOIQgL8FVIxUnQYQFOX7U8Uh"],
"merchant-10-prd" => ["api_key" => "CE-SDI0MOUHFGD4EGFP", "api_token" => "uZ41OUsuqQJUucv2C5GRaPfrYpujbH66"],
"merchant-11-prd" => ["api_key" => "CE-O3RL29F2N9SQFHFW", "api_token" => "m6W8csu83s92YtVtqRiQ8PDOEhMrNpP5"],
"merchant-12-prd" => ["api_key" => "CE-PINC8CCZMPVOWNRT", "api_token" => "uDHnraLNzbpNwbxKZU8oTsdpHN2d3nR7"],
"merchant-13-prd" => ["api_key" => "CE-2HSUVNGEFYENBZNN", "api_token" => "PJZPqOBlXNz5FkLCIt9bq8vFaLP7B7hA"],
"merchant-14-prd" => ["api_key" => "CE-R9MDZTB3I8KJK6UN", "api_token" => "TQs2s58VqLaHfuuKwPSt78LzpDlXjSzm"],
"merchant-15-prd" => ["api_key" => "CE-EFHR58TVSM0CCUKT", "api_token" => "CzzCXcQ9WY4M2pFWYXNERYQCE0seYmVD"],
"merchant-16-prd" => ["api_key" => "CE-TWN4W5IWF9ILKIIF", "api_token" => "6Pfhu69P9bJJ7HybwhxH3Bi4HsjnKU35"],
"merchant-17-prd" => ["api_key" => "CE-D1DYBR0J0ZVMGQJB", "api_token" => "4CBOxMIzm0HjbA9i9B3v5e4uV7L5wEIO"],
"merchant-18-prd" => ["api_key" => "CE-3VPKGXZMKDEXYV7G", "api_token" => "nAQ2RKmWDq20PNe0jnKg0XrTdaynrhUS"],
"merchant-19-prd" => ["api_key" => "CE-3SO1FZ5JBPREEHP2", "api_token" => "PyMdJkPSEcDWL4iF6VL4vN9qXppMGyoa"],
"merchant-20-prd" => ["api_key" => "CE-EHEFTXBQHVXTKF5M", "api_token" => "Z2iwbEUJ0LFybdDtpdkA9ujLulIcsBkf"],
"merchant-21-prd" => ["api_key" => "CE-WU6X34CNUXYRVKRC", "api_token" => "vT8I9pNU1ctKe0eQm70TWnFcp4UZmWmj"],
"merchant-22-prd" => ["api_key" => "CE-ZE3YTQ7NISVQSF2V", "api_token" => "2vtUQeTPpqOb17MmWrWqaeeuAY640pIO"],
"merchant-23-prd" => ["api_key" => "CE-APZOGDWHL4V6QUVX", "api_token" => "ShsNyPrSQTrDKPqduPAmr7QpiJ5scUAc"],
"merchant-24-prd" => ["api_key" => "CE-FNUFU9TNUOGBOKFW", "api_token" => "0DxB4PMTkV7Li3WFFwxwbc2mtD8rRdBC"],
"merchant-25-prd" => ["api_key" => "CE-JG0OZEBLR7CSB7UU", "api_token" => "q1A5oJaUHQACdPhzVYHvzNkLJsDoQfZ9"],
"CLEAN" => ["api_key" => "VC", "api_token" => "CE"],
"SPV" => ["api_key" => "SAMBEL", "api_token" => "CE"],
"KHUSUS" => ["api_key" => "MART", "api_token" => "CE"],
"Project AB" => ["api_key" => "-", "api_token" => "TOBA"],
"ANGEL" => ["api_key" => "VOUCHER", "api_token" => "GAMING"],
"INTER" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"TG Group" => ["api_key" => "CE-PZSAFRAXFBHNBSMJ", "api_token" => "6l3BOLGBGP8NGjTlCYsrznAPH3bhwVA9"],
"manager sambel789" => ["api_key" => "CE-WQ6GUSGTKWODTS0K", "api_token" => "Z7ls7V3QGFzt2YUEiKP1eTTu0ZW7Bg0y"],
"supervisor sambel789" => ["api_key" => "CE-M50W0XTYC9CG5DHU", "api_token" => "lsh5dDV5LvfVOyKtMNmLjyk6dONSqsFO"],
"CU8" => ["api_key" => "CE-E0ZHMMNGDHFAR3J0", "api_token" => "5c1fePJaGBA6rvp787UeeWLbVjLvdN6Y"],
"RU8" => ["api_key" => "CE-G0OGU8UONCHIMCAY", "api_token" => "VPOildv99KsjiowJTZkwi9onh9X8MzeG"],
"FUJI" => ["api_key" => "PREMIUM", "api_token" => "CE"],
"PT Jekka Sallo" => ["api_key" => "CE-MU1ACSSGNECHVAI6", "api_token" => "WvF4QUVKAtyA6p5SUHKeINC2xYjQuCHb"],
"FYP" => ["api_key" => "SHOP", "api_token" => "CE"],
"WD Sambel789" => ["api_key" => "CE-PV324UBFXKHQWFDD", "api_token" => "tiwDSt42A4b1m0PzJrENhgJ1KnelVzJz"],
"Cerita" => ["api_key" => "T", "api_token" => "CE"],
"PAUS188" => ["api_key" => "CE-EVXQ0Q0VIWJBPNAX", "api_token" => "kHdhqoEKCYxjNFDCWK6QhcqsXSAtNur8"],
"PAUS" => ["api_key" => "SHOP", "api_token" => "CE"],
"Lucky" => ["api_key" => "CE-0RAHHTPAGJHPWMPG", "api_token" => "rcywC7q8bO2ox6nzvgS76p7fG7fiL0WW"],
"merchant-26-prd" => ["api_key" => "CE-GMEESMVCJMRMBCCD", "api_token" => "YUoWougnZh15qeJxnrxz24TWOiRlC1Ur"],
"merchant-27-prd" => ["api_key" => "CE-RYNCBDX612KOQXJO", "api_token" => "Ke8KAP8sGKqYELJceekQNPUa347OKGMZ"],
"merchant-28-prd" => ["api_key" => "CE-REUDJ6ZPJUQLFMLP", "api_token" => "IfW9A0p3gSfiRVP0Hs5A62MiCblQP8Jz"],
"merchant-29-prd" => ["api_key" => "CE-HADNJDEZHJUGZPXW", "api_token" => "mn7v5PfH189Zc4snJZq5hrvSmDaNybhK"],
"merchant-30-prd" => ["api_key" => "CE-CKOOARHICWGXYGSY", "api_token" => "LhL5YoO4WA1DClgaiJ10eD3ptfX1Hjsg"],
"multiechopradana" => ["api_key" => "CE-MRN755OL83HXSTFN", "api_token" => "JJD6ttesN9wWRzsJztuHW4WzH0zMxEde"],
"v1073" => ["api_key" => "CE-5Q9GVHJEUXK6DDUJ", "api_token" => "02HwZWSGBYqae4Rw5nLGL1trf5qdykff"],
"Butter" => ["api_key" => "CE-AI3GUIX1DW6Y8KKT", "api_token" => "a1BldBQDKCuvDy5WGPj4f2jP5BTSeIQO"],
"WARGA" => ["api_key" => "STORE", "api_token" => "CE"],
"MPCRN" => ["api_key" => "CE-YGQST8CGCRPEFVDX", "api_token" => "hmYBwAkdOZLR6hZyngXGpTnRcYKvGIwS"],
"PLANETHOKI" => ["api_key" => "STORE", "api_token" => "CE"],
"Multi Jaya Kencana" => ["api_key" => "CE-7ZMQF62GUNV2WZFT", "api_token" => "ypLSoA1ZFIwz2sIcqPvC1oDNgqMC9BWr"],
"HOKI" => ["api_key" => "PONSEL", "api_token" => "CE"],
"MULTI" => ["api_key" => "ECHO", "api_token" => "PRADANA"],
"JOAN" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"VICTORY" => ["api_key" => "MART", "api_token" => "CE"],
"FAST" => ["api_key" => "ONLINE", "api_token" => "MART"],
"DETIK" => ["api_key" => "SALAKGO", "api_token" => "STORE"],
"india" => ["api_key" => "CE-3THG9ZK2KLBXX1TX", "api_token" => "TsFXKtgNC3Gicp18dYu0TMimMhvPpfb2"],
"TipTop" => ["api_key" => "CE-PFSBNA7UEB8VV8BN", "api_token" => "VfeCixulfkzvRMYLV9HrvcOhVRvZUGX0"],
"Asira" => ["api_key" => "CE-X56467FLIZEKJZPU", "api_token" => "o4oplxnnl12WwhPikfvs5Fr5QmJ3TSTU"],
"MM" => ["api_key" => "GADGET", "api_token" => "CE"],
"DEJI" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"merchant-31-prd" => ["api_key" => "CE-SNI8FV0MWXNAFAIB", "api_token" => "KDrqAvkGoiZH0n9aHdCuHk7K4GirsFHK"],
"merchant-32-prd" => ["api_key" => "CE-AD9XDKFQHRNZB3I0", "api_token" => "wfR1fEfdI5ENJMGCYsSX333i7xR3YA7l"],
"merchant-33-prd" => ["api_key" => "CE-FI736U0WQHQLFVGU", "api_token" => "fLBthWGK0qXeZVtGruJ6GQkF6EnKCoFl"],
"merchant-34-prd" => ["api_key" => "CE-0JSRMCQ3YLKLPW8Y", "api_token" => "yoLG0nebdvEg9oTYEcU1BmKb6QTvzaRf"],
"merchant-35-prd" => ["api_key" => "CE-JZHLAW0LXBNNZFM4", "api_token" => "II5flzXq40guU3a3XCmy02cm0cQLM82G"],
"merchant-36-prd" => ["api_key" => "CE-SURJ69E5VKT86VQR", "api_token" => "JYJ1epYnhqScV0rLzWgPOrVwk2Mu33oc"],
"merchant-37-prd" => ["api_key" => "CE-YZRLZVYIOOLI0TRY", "api_token" => "RHzrOLbgpXCcrMlcTKRpn2JhBc1e00eM"],
"merchant-38-prd" => ["api_key" => "CE-ZKKYVHWRHGKELEN2", "api_token" => "EeUca0lX7I5MbY1YPcdFgWAfTWDIaMKW"],
"merchant-39-prd" => ["api_key" => "CE-1MFFGVIPAGLM5DOQ", "api_token" => "sNP0WreJ1ddVNRb8p8utOTDtZQHNqfH0"],
"merchant-40-prd" => ["api_key" => "CE-3BAMSROGGEFBWHGM", "api_token" => "m0c9VbkhedLo68u1h4vtPSKbEX9JYFro"],
"CETAR" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"Kasteng" => ["api_key" => "CE-CL9CCZ4JAV3VYWAD", "api_token" => "ad5EsvvfkoXb5DVdTMR149CNrRvGmggQ"],
"367MART" => ["api_key" => "CE-DWHZK3PYOGLGFRS4", "api_token" => "of4Il3yCsFlNv4wHiCSNfdyDMaxqlkkK"],
"Metaverse" => ["api_key" => "CE-ME7YZM9FSAL5TWI0", "api_token" => "UecwrB3Vjym6XHzMqTtLfLqOPVqYjQdR"],
"Solusi Logika Nusantara" => ["api_key" => "CE-FQGSVTJR8NMVPU6B", "api_token" => "rR2UwPAGf1alHaeRJwFlAk80EPM9lLdk"],
"LAngsur jaya" => ["api_key" => "CE-OT0LBPY8CNQPWL3I", "api_token" => "ty6wIKnz9iSu7J90mmu15ltZVLaqmxtE"],
"Panen" => ["api_key" => "ID", "api_token" => "CE"],
"TOKO" => ["api_key" => "ELEKTRONIK", "api_token" => "HERU"],
"SATU" => ["api_key" => "JIWA", "api_token" => "MART"],
"merchant-41-prd" => ["api_key" => "CE-S9WQGZ7LTTNONJR9", "api_token" => "qwUeun6ZEUvwuhymp7PLiOH6cRXbFcLZ"],
"merchant-42-prd" => ["api_key" => "CE-7SKFBAPANJKLCXTV", "api_token" => "xtQWEtcAJuEvyinUY29Mv4xIGziDNeYZ"],
"merchant-43-prd" => ["api_key" => "CE-GGF0YKKJDIZENUVN", "api_token" => "nL69iBres8LsT3IRFPzrLz7yMK2OgwgM"],
"merchant-44-prd" => ["api_key" => "CE-R8S4HX7ZTUSBSQLA", "api_token" => "r1BsafeJABZJCNyxTdkYDbbLDlmelDWH"],
"merchant-45-prd" => ["api_key" => "CE-BI4YJXVUPJQNWLOL", "api_token" => "XxSFfWR5BDthVmCtYsM1WAStLyDVCjJJ"],
"Rizal Gadget" => ["api_key" => "CE-DI2NKK75T5WSPZMW", "api_token" => "TpVcOgkO1SQNAOlWM0fQcWF1Vw11ENab"],
"SINAR" => ["api_key" => "OPTIK", "api_token" => "CE"],
"TEKNO" => ["api_key" => "CELLULAR", "api_token" => "CE"],
"Genit" => ["api_key" => "CE-AKIL3JSXWPRHRCXE", "api_token" => "aDHVr7ECgrTr149kUcosR414duZTOgeL"],
"WOW" => ["api_key" => "MARKET", "api_token" => "CE"],
"SAYAP" => ["api_key" => "MARKET", "api_token" => "CE"],
"JAYA" => ["api_key" => "MART", "api_token" => "CE"],
"V1074" => ["api_key" => "CE-CJYJUR3ZZEPNEZMP", "api_token" => "hnW1r9ATonwQQyR3w2tqdSeQJgmbw20G"],
"V1075" => ["api_key" => "CE-7HSF5P2NDBP6LEZD", "api_token" => "3dhUebZDYa5mXmhYEAb543uJ4jZunBcA"],
"Istana Pasti Berhasil" => ["api_key" => "CE-0AVFT69S1TP77QAP", "api_token" => "xFdgUdV9yYNWX4WyHKqHoTIxvCuv2Nm3"],
"NOBLE" => ["api_key" => "STORE", "api_token" => "CE"],
"MDGWIN" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"PT" => ["api_key" => "GEMILANG", "api_token" => "KARYA"],
"Princess Lind" => ["api_key" => "MD", "api_token" => "CE"],
"Geovanny Kerluke" => ["api_key" => "IV", "api_token" => "CE"],
"Project AB" => ["api_key" => "-", "api_token" => "GUNUNG"],
"Bm engine" => ["api_key" => "CE-VOS0RIUKJ2HY5U3A", "api_token" => "gcXQUSuOrnxv06trDAoWPQHUls3XyYrj"],
"RRQ" => ["api_key" => "STORE", "api_token" => "CE"],
"Test Delete Ya" => ["api_key" => "OM", "api_token" => "CE"],
"v1078" => ["api_key" => "CE-SQ2OEQCBD4ZRHI5C", "api_token" => "Htovb9q7aSp1pht5gJbxeORxIy97XN50"],
"Bonus Cbo" => ["api_key" => "CE-E3HK52HXNRJ59XTQ", "api_token" => "u58O9YpPmOsZuvgNQvO4N7fdqKV0ivLh"],
"QUEEN" => ["api_key" => "MART", "api_token" => "CE"],
"TarikTunai" => ["api_key" => "CE-8N5ZMXNZNO6UECLH", "api_token" => "OwCXba8XG6qW0VFQnUQ75hBcquQyng4G"],
"skst dari pzm" => ["api_key" => "CE-QRKU5TVJIUUIL81Y", "api_token" => "XqHd7P4WPJ6h9GZ4ID0bpPvqUwHF8SXH"],
"h-global-pzm" => ["api_key" => "CE-RLHWBPCELKL6YTQZ", "api_token" => "uNdBS0PK0SXVg4Y80NUyC53xxASARUHt"],
"h-local-pzm" => ["api_key" => "CE-ATYCHKPRA7Q1C2LU", "api_token" => "wbFEEEMd4PAvHugDvIeyCgJmXMb3YFQK"],
"h8-baru" => ["api_key" => "CE-KMELC1SEJV6FTXTP", "api_token" => "S8Fp9Y6HwiUOAmIgqyWWssBw03mbqTH0"],
"gemesh" => ["api_key" => "CE-REFBFL6MJ3AJHMPI", "api_token" => "igaos68THAmSCDadhsIX5nYxg07TIJVB"],
"LAVIDA" => ["api_key" => "SHOP", "api_token" => "CE"],
"WIN" => ["api_key" => "WIN", "api_token" => "STORE"],
"BERKAH" => ["api_key" => "STORE", "api_token" => "CE"],
"TOPAN" => ["api_key" => "VOUCHER", "api_token" => "STORE"],
"NETPEDIA" => ["api_key" => "STORE", "api_token" => "CE"],
"HOTO" => ["api_key" => "HOTO", "api_token" => "SHOP"],
"WINGS" => ["api_key" => "SHOP", "api_token" => "CE"],
"POLA" => ["api_key" => "ZPAY", "api_token" => "MART"],
"GOLD" => ["api_key" => "MART", "api_token" => "CE"],
"PT SETENGAH MATANG" => ["api_key" => "CE-C2T6QO6PZBFBMYFL", "api_token" => "NDlOxak4fvclhjqyil5JvjUSHph82ouH"],
"GOGO" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"merchant-46-prd" => ["api_key" => "CE-YGKP1XPSSJ1CPAC9", "api_token" => "uIanLKr3eEzvgPuzWDa618a4h671YTNb"],
"merchant-47-prd" => ["api_key" => "CE-PWK87SZKVDEQYMP8", "api_token" => "MjXQjV8xocfIAoXaGNNs8tMWyaZTH0Bj"],
"merchant-48-prd" => ["api_key" => "CE-26FCJXS9Y5OZX4PL", "api_token" => "cBOeoR9rWwXIUqGprShU5rh0zsPaJVV9"],
"merchant-49-prd" => ["api_key" => "CE-TXIVVHC49FSYL6H1", "api_token" => "ZOg9FKNAxHhX9dgdv6PQspWskdektNti"],
"merchant-50-prd" => ["api_key" => "CE-TUPXF5LGJULLNBXK", "api_token" => "ZfvndQTV07KUuMdPDWHIaltS5aiAdtIp"],
"KN" => ["api_key" => "CE-DO0JIOTE9AJSJLDS", "api_token" => "SwZo0Qgfw0pmU4RPAOwTL7sJoHpEgIVA"],
"WINTO" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"ovogoal" => ["api_key" => "CE-AIKP5EXG2KWMMQCQ", "api_token" => "AAYQwgxtRts8vHT6hfgRHMjS9BHZwE1U"],
"Flush Partner" => ["api_key" => "CE-S8LYWCBTSVF1R91V", "api_token" => "0SLZ5d5zswkdbL5yh74GAhTTgz4Mf0Yf"],
"merchant-51-prd" => ["api_key" => "CE-OHA0IHT07CNZQMSR", "api_token" => "2LiFeEEMcWNx4H2dUhsqlXV5OjtP6Ii4"],
"ARENA" => ["api_key" => "STORE", "api_token" => "CE"],
"DELAPAN" => ["api_key" => "STORE", "api_token" => "CE"],
"MUJUR" => ["api_key" => "STORE", "api_token" => "CE"],
"PT" => ["api_key" => "SONY", "api_token" => "ERIKSEN"],
"INTER" => ["api_key" => "MARKET", "api_token" => "CE"],
"MDG" => ["api_key" => "NINE", "api_token" => "NINE"],
"v1076" => ["api_key" => "CE-UP4JQBTCMRXSJPTG", "api_token" => "AzohdlwYZ6Yb3gdVneGMQ2rokvz3qTNn"],
"APIZEN" => ["api_key" => "STORE", "api_token" => "CE"],
"henggam" => ["api_key" => "CE-02OQU9FOTUDM1MFT", "api_token" => "wS7tCusFlsCiM0yWl70acIDNygHyJkZ4"],
"AB" => ["api_key" => "-", "api_token" => "SEBESI"],
"Project AB" => ["api_key" => "-", "api_token" => "MENTENG"],
"RESTU" => ["api_key" => "STORE", "api_token" => "CE"],
"CENTER" => ["api_key" => "GAME", "api_token" => "CE"],
"AB" => ["api_key" => "-", "api_token" => "RAJA"],
"AB" => ["api_key" => "-", "api_token" => "BINTAN"],
"AB" => ["api_key" => "-", "api_token" => "SUMBA"],
"AB" => ["api_key" => "-", "api_token" => "RINJANI"],
"MARS" => ["api_key" => "CE-NGIIOKCKHNYIFA5D", "api_token" => "CxgCl7Y6SGO6AaVArOKAvJjVIHBjCQbB"],
"NEPTUNE" => ["api_key" => "CE-EIP3GHF3TVSNTY84", "api_token" => "0XAse6I2CdP3nwjPR9t2UH9cNHBUXvoS"],
"Marss" => ["api_key" => "CE-TKCAETYCZ6D5ANZ1", "api_token" => "fgNTd3co2lPq1bBSv0qYh8Z7oev43J72"],
"merchant-52-prd" => ["api_key" => "CE-P8TTEJXSXOLNZLRO", "api_token" => "BewONDI8ggAKmrmhAwlWY1xP5iLfJfrj"],
"merchant-53-prd" => ["api_key" => "CE-TPRE2AF4U0XA8UNG", "api_token" => "P7WgS5lP4pulaqm5zZhx2CmvsVdWNeFa"],
"merchant-54-prd" => ["api_key" => "CE-YYE5FFWDVOQBPFQA", "api_token" => "TozGXKjOfqYKdqpbBaz60RtAaI2gdhc1"],
"merchant-55-prd" => ["api_key" => "CE-ELHT1GE42FUXYT17", "api_token" => "eU0PELIzYBKgtKQ7c39Q9fjcNTz5UPRl"],
"merchant-56-prd" => ["api_key" => "CE-J7NCPUY7BBJFA8YD", "api_token" => "vjoLT9ypWvSWlSGx9CcdY2RbONHPe96E"],
"merchant-57-prd" => ["api_key" => "CE-YCFWLXAUJI3T6KKX", "api_token" => "zuGPq9pT4L96Lump9IVm2yTRvRwxESQk"],
"merchant-58-prd" => ["api_key" => "CE-OI25S44PEVKQVFJS", "api_token" => "cLbjVcQpGI5oHI3jOYzJfRvboERdk76E"],
"merchant-59-prd" => ["api_key" => "CE-MVOZKICUWIIX6SBQ", "api_token" => "5Ci60nyiEqG3GbbJVjBvN71WcmwzwjEZ"],
"merchant-60-prd" => ["api_key" => "CE-Q7G5ZQFE6TJCED8P", "api_token" => "zIfGvsicPkQgs6I7NLQZk9kKPwlLoepB"],
"merchant-61-prd" => ["api_key" => "CE-SFIHHLX0Y93EBM1S", "api_token" => "LeKHlAqwo8Gnm5nlgWdQCxANnbNnJD12"],
"merchant-62-prd" => ["api_key" => "CE-YKPTDBR5ZPMENNUU", "api_token" => "MjvqK4tXzXr2NEgowPxUqwFcPWvSFspg"],
"merchant-63-prd" => ["api_key" => "CE-AM8PA4YMCWVQSHEF", "api_token" => "qzWTFP5pme6GB7AhgXJunwy1d3o4PVfn"],
"merchant-64-prd" => ["api_key" => "CE-SAKPKIURFK10ELJH", "api_token" => "aUvhjTDQ5sQHL2ULrS6h836s0Re6zTEI"],
"merchant-65-prd" => ["api_key" => "CE-TYKU6LAMN9SZF7PI", "api_token" => "nfHhSyOziRPw7ye9luw2cn9n9JsQRxia"],
"TIME" => ["api_key" => "STORE", "api_token" => "CE"],
"RAKSASA" => ["api_key" => "SHOP", "api_token" => "CE"],
"HAHA" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"TOKO" => ["api_key" => "SEBELAH", "api_token" => "CE"],
"PRO" => ["api_key" => "MARKET", "api_token" => "CE"],
"RAGIL" => ["api_key" => "SHOP", "api_token" => "CE"],
"HIU" => ["api_key" => "GAMING", "api_token" => "STORE"],
"INTER" => ["api_key" => "GAMING", "api_token" => "STORE"],
"Andoravaldi" => ["api_key" => "CE-POWN7OVJWPSFOCTW", "api_token" => "0zVJ3tXc2ALZtuh7pLh7Gk4TXjGFltIL"],
"V1082" => ["api_key" => "CE-P8VHFC8M5RZPMKPY", "api_token" => "HELjzYYIOVELLlCnVAWr5c6GZYq1DmX7"],
"V1084" => ["api_key" => "CE-ZZKOA1KAXYSQWIKH", "api_token" => "kGNPt2Y6sOznBVqUdSxUycWkd6BtJjkm"],
"v1077" => ["api_key" => "CE-Z99XVLHBVSKMW1XF", "api_token" => "Zg0gtqR6JuLKFMCD37fO7B2FSrLtZOra"],
"Miss Ruthie Weber" => ["api_key" => "II", "api_token" => "CE"],
"v1080" => ["api_key" => "CE-8WJ26T3BU0JLZNTS", "api_token" => "996j0CbZT8eDrgGGuuhEahaG2nWJg4Jb"],
"TAHU" => ["api_key" => "JAYA", "api_token" => "STORE"],
"OTANSTEAM" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"OBOR" => ["api_key" => "STORE", "api_token" => "CE"],
"IRONCELL" => ["api_key" => "CE-PUJVCIIEDGA4FLAX", "api_token" => "uiRhiFx9Rz14EAGX2iub1SQnjCaNS4yJ"],
"PT TRON LIGHTS LED" => ["api_key" => "CE-A7K3OC6ACDYWIN6S", "api_token" => "WDdAMG2954mKXaQttLVcnCqJ839f05sg"],
"YUKA" => ["api_key" => "STORE", "api_token" => "CE"],
"V1083" => ["api_key" => "CE-GHIHEG13EQK6JWJ5", "api_token" => "iSvbaMAexb9ATxwLWnY6ItUBorS3AxQF"],
"Antzein Merchants" => ["api_key" => "CE-PGA4TV0JDDTTGNHP", "api_token" => "qzJjitE8U1JilmjVhVi7RYAVXtqJXoEP"],
"v1012" => ["api_key" => "CE-KHJA2E5OMED8INX7", "api_token" => "pMKGSkj2ABsRCXSGTNU4T69ldrL8ZosT"],
"Dumpling (Inactive)" => ["api_key" => "CE-RXV2FX3MGUNV6QTY", "api_token" => "DW8F6ogAk4EcE3FRuSXQlAPQmhv3NsYP"],
"Dumpling" => ["api_key" => "CE-N7SVR9RDLUVEM8F1", "api_token" => "90F6y02GMlfrenVfXZjVPzW1avv2GXNj"],
"BELLE" => ["api_key" => "FASHION", "api_token" => "CE"],
"KKMART" => ["api_key" => "CE-RJIONEFT5T5ZCEHN", "api_token" => "sc8x8MvZczhRB9cHyrpGoyo7YCuB9rAT"],
"OZON" => ["api_key" => "SHOPPING", "api_token" => "STORE"],
"OPAHOKI" => ["api_key" => "VOUCHER", "api_token" => "STORE"],
"ODIN" => ["api_key" => "SHOP", "api_token" => "CE"],
"KINI" => ["api_key" => "SHOP", "api_token" => "CE"],
"merchant-66-prd" => ["api_key" => "CE-A9VUBOTDWCLWOLUL", "api_token" => "bDntResgdIVcnummY4SILM7SdIq7hN5x"],
"merchant-67-prd" => ["api_key" => "CE-IV34E1LWZDLPONKN", "api_token" => "3OHoJRbJgv5LhuOFbPCbKfKL4QGs1GNF"],
"merchant-68-prd" => ["api_key" => "CE-CKOUPWQNVAKZHXY3", "api_token" => "vp09su2JgOPZHY5ISMe9BD7jqqjOhuCr"],
"merchant-69-prd" => ["api_key" => "CE-CRGSANBNJTMWDA1O", "api_token" => "spOYXmI42OlLBZHqLdwMJaTvGiWqVtbl"],
"merchant-70-prd" => ["api_key" => "CE-TVK0HROFPKWUUQ4T", "api_token" => "hLtvJAU5FwM9wXEWAKuNfvE0nR3UigST"],
"merchant-71-prd" => ["api_key" => "CE-XONTSEETOEZLQFFS", "api_token" => "Jn1hnEYdB6T5MBVkavxq6fTQ1KLxFG21"],
"merchant-72-prd" => ["api_key" => "CE-YUUCH7ICAXEDFXD5", "api_token" => "f6zlN3fIIwfHS3y2JzM4lAqznLVN6Oa2"],
"merchant-73-prd" => ["api_key" => "CE-XMGIUEXZQVT94F9C", "api_token" => "6GAQHXbAstSxsbVOHDU45mh63bBmJeyv"],
"merchant-74-prd" => ["api_key" => "CE-M65C9T76OHLGKMCY", "api_token" => "Or7AQ73AUcRm1mfTqFOntCeTDAaPRHep"],
"merchant-75-prd" => ["api_key" => "CE-3DNAVWGPFIG6HRKV", "api_token" => "XtDyHBzBl5806Hno9spWfKNATc9Ojgl3"],
"merchant-76-prd" => ["api_key" => "CE-MN4A81DKW3JN4WLL", "api_token" => "J9b8bNdIdlxuVXj3zXCPU3atkpNeLuwu"],
"merchant-77-prd" => ["api_key" => "CE-BHQH5KVADRQTXHXK", "api_token" => "E0LXpB9Mn7YkIAdozRoAlebUb4Kb95Ek"],
"merchant-78-prd" => ["api_key" => "CE-PAKBZ3DUR9UHE1UJ", "api_token" => "7rprRtoBCr8G4bOYO1poQhItZBfBqCe1"],
"merchant-79-prd" => ["api_key" => "CE-DRNW3MQJQ1NI1ZFI", "api_token" => "saAaFef4diOHMSJzsIRU6SVT6Ljg6xNi"],
"merchant-80-prd" => ["api_key" => "CE-UUYAOASEVO09UWBC", "api_token" => "S7OU6tNtA13BgDc5lKGdSGUtYFDtVpcp"],
"merchant-81-prd" => ["api_key" => "CE-JTIYQNDCWE19K037", "api_token" => "3K9OPpyMbToBp1PbW2ePbLjgG5N89iln"],
"merchant-82-prd" => ["api_key" => "CE-ZEYJFSGPG0LNZZ4O", "api_token" => "PIJ8SHsT0LlvBlj8JgRtbtEp6w6IQYLD"],
"merchant-83-prd" => ["api_key" => "CE-W8Y9EOTSHZMHIHNH", "api_token" => "NBAPSWZPC7YL9As3qWbhhiLP1bcJ4a7C"],
"merchant-84-prd" => ["api_key" => "CE-WUWHTVOXVUW84ULB", "api_token" => "chx8fmETn9UagIW9vrF7AMqbvMpm4wy3"],
"merchant-85-prd" => ["api_key" => "CE-ID36ALZM9JW0CG5A", "api_token" => "PZh5icRQlnlBdk30iqCv8slbCewph2Tx"],
"merchant-86-prd" => ["api_key" => "CE-OSBB5LQ1WHTXCBIC", "api_token" => "kwQQEAvGlWryFiSqe23b5RWLgECeDsO7"],
"merchant-87-prd" => ["api_key" => "CE-ATCOK7LDCNWJXAEO", "api_token" => "yBt1gCNHQYX2Ryug1Zt3NGII4Oo4jO8p"],
"merchant-88-prd" => ["api_key" => "CE-FAG8YECXEWWJ8WVR", "api_token" => "Hw49H5mkhF8iJWbZXYGi0lPax9HrwxAk"],
"merchant-89-prd" => ["api_key" => "CE-USTIZZ5P45U87RS0", "api_token" => "jYvOycsRWK4I96YsaWOIi42B77AeyaCf"],
"merchant-90-prd" => ["api_key" => "CE-KNHPP7OKUHGK8GIT", "api_token" => "QNWv7WRuasarqyqg1nkRrcIrN6pSMIWc"],
"merchant-91-prd" => ["api_key" => "CE-BDVYNQ1ZGICPEND5", "api_token" => "8OQLVYQcc7hTLcccEA5BWcKVLzLUrRPo"],
"merchant-92-prd" => ["api_key" => "CE-BGOZXFGQPS5IC638", "api_token" => "aPwBE9iPYx5LwNSJNTyibq0xa2hYa9nm"],
"merchant-93-prd" => ["api_key" => "CE-NIDZD05O09PTD1ID", "api_token" => "UbSriohJdrS2WUUQNSe0heoFz9jVCmI6"],
"merchant-94-prd" => ["api_key" => "CE-NK2RVSL1CS1IWDHS", "api_token" => "fuwbpNTdaPsemCv7IaKpLoaj4Ls8QBRL"],
"merchant-95-prd" => ["api_key" => "CE-OYVDWHO1PIS6OFOA", "api_token" => "4xo16bqcf0P67akxwjstGnZtS4fo3XW2"],
"merchant-96-prd" => ["api_key" => "CE-XZMO6XKZUNZ1KYAZ", "api_token" => "p6wUm0MpI7l3YMHOEVblDlcLpjjNhP1R"],
"merchant-97-prd" => ["api_key" => "CE-WEGM0JKTUBHW2HVF", "api_token" => "ASQDRwS1znXSyL76DJ0qvLsilInDJEsw"],
"merchant-98-prd" => ["api_key" => "CE-BIM9IWPITGN9LLKC", "api_token" => "K9E3hFzLsykYVMHjUwCItMsbSkdKLAXw"],
"merchant-99-prd" => ["api_key" => "CE-ILYFKOSTIY1JM4VI", "api_token" => "TTiMsc5IWrze9UxqCZIQvrYDcjv3Sb73"],
"merchant-100-prd" => ["api_key" => "CE-QG6ENNML59YV2GRP", "api_token" => "Tc9JTPWBDBn6YmY0EI4ePho564X4ZlTN"],
"EIGHT" => ["api_key" => "SHOP", "api_token" => "CE"],
"SEVEN SHOP(Incactive)" => ["api_key" => "CE-A5OZDDBZ1BRJE2LI", "api_token" => "sW5fTVF1vPt5eWOJCUHQkFKvkvk7e9J9"],
"Migration Direct" => ["api_key" => "CE-IX3BN4NV3EXXU0KO", "api_token" => "7wiPwBSYQCgXnPu5fWLzkQJXtyGq9xGe"],
"PUMA" => ["api_key" => "MARKET", "api_token" => "CE"],
"Distro Andara" => ["api_key" => "CE-PXOZT1W6T7CTHFXE", "api_token" => "y7c0gZuhwzADnUGM2VMOWTIU25ioZeSt"],
"MAMI" => ["api_key" => "MART", "api_token" => "CE"],
"RAJA" => ["api_key" => "MART", "api_token" => "CE"],
"MARCELL" => ["api_key" => "MART", "api_token" => "CE"],
"JOJO" => ["api_key" => "MART", "api_token" => "CE"],
"LOOP" => ["api_key" => "MART", "api_token" => "CE"],
"HORE" => ["api_key" => "MART", "api_token" => "CE"],
"HALO" => ["api_key" => "MART", "api_token" => "CE"],
"OMODA SHOP (in active)" => ["api_key" => "CE-GP4LBE2TGYYCW2T8", "api_token" => "c6UoUlE4pWgKAZbn2difppyQXfsfELit"],
"RP" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"MAJESTIC" => ["api_key" => "VOUCHER", "api_token" => "CE"],
"MENTARI" => ["api_key" => "MART", "api_token" => "CE"],
"BAGUS" => ["api_key" => "MART", "api_token" => "CE"],
"MobileXpress Shop" => ["api_key" => "CE-JFZ90YZJZZ6QVIYS", "api_token" => "5Y0jNp8U0t2ka6ofb91r5EZ2j5We70rd"],
"Serenity Shop" => ["api_key" => "CE-LTQHLU9PC8H093O3", "api_token" => "7Pv170atXduVLK8unNE5H0XtL2AVRIMW"],
"MONTANA SHOP (In Active)" => ["api_key" => "CE-9LVUYKCL2GDFEMLG", "api_token" => "7SW9MK3JplZBDZCpRc5Mw8fwkMZrhFKv"],
"NAGA" => ["api_key" => "ITEM", "api_token" => "STORE"],
"AB" => ["api_key" => "-", "api_token" => "NUSA"],
"AB" => ["api_key" => "-", "api_token" => "BUNAKEN"],
"AB" => ["api_key" => "-", "api_token" => "TORAJA"],
"AB" => ["api_key" => "-", "api_token" => "WAKATOBI"],
"AB" => ["api_key" => "-", "api_token" => "BROMO"],
"AAN doang" => ["api_key" => "CE-8MJDRNP7YTO1HMZG", "api_token" => "pS0S29O9ZBIfvKBwBxhNV1xMXzy7DQiu"],
"AAN" => ["api_key" => "CE-YJBFW8RZ4OTQSJCS", "api_token" => "2sFBABg5Oa50RqwLGdVWcJJrO5koM3G7"],
"PERDANA" => ["api_key" => "MART", "api_token" => "CE"],
"AZURA" => ["api_key" => "FASHION", "api_token" => "CE"],
"TPT" => ["api_key" => "STORE", "api_token" => "CE"],
"hengthai" => ["api_key" => "CE-YV4HQOQ3RHOOE1JK", "api_token" => "95JtyFz2LOMDGtgxPf7Jz1w1NygOOLEw"],
"PC" => ["api_key" => "VOUCHER", "api_token" => "STORE"],
"BERKAH" => ["api_key" => "MM", "api_token" => "SHOP"],
"antiio" => ["api_key" => "CE-WSQZE3QL9SMJRWIQ", "api_token" => "Wq2Sv7sfqP9CNpU6g0rwhmsPKexGqz15"],
"ATLAS" => ["api_key" => "CE-QDHMTA7KKP4XRN2P", "api_token" => "GrBtafeOOXvy6xTj1c1dF8FDLJrpQ6Nh"],
"AB" => ["api_key" => "-", "api_token" => "LOSARI"],
"hengpulau" => ["api_key" => "CE-OMX1DQNUJEH1VX8J", "api_token" => "KUXYqHFMMmFeQm3IKPocPoFerzwBiLdv"],
"CAHAYA" => ["api_key" => "CELLULAR", "api_token" => "CE"],
"TOPUP" => ["api_key" => "MUMER", "api_token" => "SHOP"],
"BAKA Private Wallet" => ["api_key" => "CE-DVV0FSC039XPH22H", "api_token" => "76XrKj4NBOwOChSTB5GOg6jlkE4fsQkC"],
"MIRA" => ["api_key" => "MAJU", "api_token" => "ABADI"],
"SQGQ Tampung" => ["api_key" => "CE-BEEHRIY51LSYO3OM", "api_token" => "w8TbBIE2tJzF2om3HVcX9RjHBHVdC7tb"],
"SQGQ" => ["api_key" => "SPV", "api_token" => "CE"],
"WD" => ["api_key" => "SQGQ", "api_token" => "CE"],
"Terbang77" => ["api_key" => "CE-3V1PJ9W3IEIDQDHU", "api_token" => "RupPN0etwe1Wtz6zyKF7mHWTYXyzw1V1"],
"v1003" => ["api_key" => "CE-4L2SY02BADF86HLM", "api_token" => "2PhAhkrpFkEzTp3KJE95nZlkjjcqVvz3"],
"V1005" => ["api_key" => "CE-WKUXZJMJN4QMVPJX", "api_token" => "Vl8iSvkwnHunPY94pB9SfA2v600bzuvl"],
"V1006" => ["api_key" => "CE-BXYDZFTF6I1XDRR3", "api_token" => "DbUdIdvZ5jQ3tEO4Wxm6ljFPqEVdcpr4"],
"V1007" => ["api_key" => "CE-G82QUFF3TRBRRGA6", "api_token" => "N1aQiYkk71BCMHoQVMC9QVoxNqtJZA8k"],
"V1008" => ["api_key" => "CE-AG94VGTR9XHYT9FK", "api_token" => "Px2WCsth0ZfeFS4xvygxk3ooWGwCC6I2"],
"V1009" => ["api_key" => "CE-Q45RUJN4MWM5XH1F", "api_token" => "URXsRhtuIokGnmT45y7QxYThQJ7AV5OG"],
"V1010" => ["api_key" => "CE-ECDLB5LBQM8IT6FO", "api_token" => "gHs4hSu3daBoyVbTILmfWjvQuoBnTIzW"],
"V1013" => ["api_key" => "CE-NEIGTVQ1JCMF1IYS", "api_token" => "tyVDFEqrwHFhNdXDrFqZ4D37KWeiT5tG"],
"V1054" => ["api_key" => "CE-K6GERDXQDUUPHON5", "api_token" => "FG2NR53ScJ6i6fTmu8AzrUsN2FP9X8Aq"],
"V1079" => ["api_key" => "CE-WDOUF5FKMIWSFKMV", "api_token" => "ZMSHIrWQ3MUjoTdBdXdnzlIdHjYYDeWn"],
"Pgwin" => ["api_key" => "CE-AYIKDU2SWO2OL7K9", "api_token" => "QozKk7bvjg5ctMNdmB5OIwTWY1pwJbnn"],
"Pgking" => ["api_key" => "CE-PBQSKNTC8D3CHOQU", "api_token" => "kRKb4HIbPfbnDtO2H4SXhagSD6NFffCV"],
"MINIMARKET" => ["api_key" => "ABENG", "api_token" => "CE"],
"LEGIAN" => ["api_key" => "PULSA", "api_token" => "STORE"],
];
?>
